<?php

/**
 * Implements hook_block_info
 */
function valorem_balance_general_block_info() {
  $blocks = array();
  $blocks['info'] = array(
    'info' => t('Balance General Activos')
  );
	$blocks['info2'] = array(
    'info' => t('Balance General Pasivos y Patrimonio')
  );
  return $blocks;
}

/**
 * Implements hook_block_view
 */
function valorem_balance_general_block_view($delta) {
  $block = array();
  switch ($delta) {
    case 'info':
      $block['subject'] = '<p class = "title">' . t('BALANCE GENERAL') . '</p>'. drupal_render(drupal_get_form('valorem_balance_general_form'));
      $block['content'] = '<div class = "nota-junta-up">' .l('super', 'http://superfinanciera.gov.co/web_valores/?MIval=Fechas_inf_fin&Tipo=066&Codigo=017&dibujo=simevcab.gif&titulo=Entidades%20Encontradas', array(
      	'attributes' => array(
      		'class' => 'super', 
      		'target'=>'_blank'
      	)
			)) . '  <div class = "millones">(' . t('Millones de pesos') . ')</div> </div>' . valorem_balance_general_listado();      
      
      break;
		case 'info2':
      $block['subject'] = '<p class = "title">' . t('BALANCE GENERAL') . '</p>';
      $block['content'] = '<div class = "nota-junta-up">' .l('super', 'http://superfinanciera.gov.co/web_valores/?MIval=Fechas_inf_fin&Tipo=066&Codigo=017&dibujo=simevcab.gif&titulo=Entidades%20Encontradas', array(
      	'attributes' => array(
      		'class' => 'super', 
      		'target'=>'_blank'
      	)
			)) . '  <div class = "millones">(' . t('Millones de pesos') . ')</div> </div>' . valorem_balance_general_listado_dos();      
      
      break;
				
    default:
      # code...
      break;
  }
  
  return $block;
}

/**
 *  function  balance_general_listado
 */
function valorem_balance_general_listado() {
  $id_anterior = 0;
	$id_actual = 0;
	if (isset ($_GET['id_periodo1']) && isset ($_GET['id_periodo2'])) {
		return construir_consulta($_GET['id_periodo1'], $_GET['id_periodo2']);
	} else {
		$trimestre_actual = trimestre_actual();
		$ids = explode(',', $trimestre_actual);
		$id_anterior = $ids[0];
		$id_actual = isset($ids[1]) ? $ids[1] : 0;
		return construir_consulta($id_actual, $id_anterior);
	}
}

function construir_consulta($id_actual, $id_anterior) {
	$respuesta = array();
	$respuesta = '<div class = "balance_general table-type-A column_count_3">';
	$respuesta .= '<div class = "title">
		<div class = "column_1">' . t('Nombre') . '</div>
		<div class = "column_2">'.formato_fecha($id_actual).'</div>
		<div class = "column_3">'.formato_fecha($id_anterior).'</div>
		</div>';
	$respuesta .= balance_general_respuesta('DISPONIBLE', '11', $id_actual, $id_anterior);
	$respuesta .= balance_general_respuesta_app('INVERSIONES TEMPORALES', '1', '999', $id_actual, $id_anterior);
	$respuesta .= balance_general_respuesta_app('DEUDORES', '2' , '999', $id_actual, $id_anterior);
	$respuesta .= balance_general_respuesta_app('Clientes', '2', '010', $id_actual, $id_anterior);
	$respuesta .= balance_general_respuesta_app('Casa matriz', '2', '030', $id_actual, $id_anterior);
	$respuesta .= balance_general_respuesta_app('Vinculados economicos', '2', '040', $id_actual, $id_anterior);
	$respuesta .= balance_general_respuesta_app('Directores', '2', '050', $id_actual, $id_anterior);
	$respuesta .= balance_general_respuesta_app('Socios y accionistas', '2', '060', $id_actual, $id_anterior);
	$respuesta .= balance_general_respuesta_app('Deudas dificil cobro', '2', '200', $id_actual, $id_anterior);
	$respuesta .= balance_general_respuesta_otros2('Otros deudores', '2', array('070','080','090','100','110','120','130','140','150','160','170','180','190'), $id_actual, $id_anterior);
	$respuesta .= balance_general_respuesta_app('Provisiones deudores', '2', '210', $id_actual, $id_anterior);
	$respuesta .= balance_general_respuesta_app('INVENTARIO', '4', '091', $id_actual, $id_anterior);
	/*********NO APLICAN**********/
	//$respuesta .= balance_general_respuesta('Materias primas', '1405', $id_actual, $id_anterior);
	//$respuesta .= balance_general_respuesta('Productos en proceso', '1410', $id_actual, $id_anterior);
	//$respuesta .= balance_general_respuesta('Productos terminados', '1430', $id_actual, $id_anterior);
	//$respuesta .= balance_general_respuesta('Materiales repuestos y accesor', '1455', $id_actual, $id_anterior);
	//$respuesta .= balance_general_respuesta('Inventarios en transito', '1465', $id_actual, $id_anterior);
	//$respuesta .= balance_general_respuesta('Otros inventarios', '0', $id_actual, $id_anterior); // ?
	//$respuesta .= balance_general_respuesta('Provisiones inventarios', '1499', $id_actual, $id_anterior);
	$respuesta .= balance_general_respuesta_app('DIFERIDOS', '3', '999', $id_actual, $id_anterior);
	$respuesta .= balance_general_respuesta_otros2('OTROS ACTIVOS', '4', array('999','092'), $id_actual, $id_anterior);
	$respuesta .= balance_general_respuesta_app('INTANGIBLES 1600', '4', '093', $id_actual, $id_anterior); // ?
	$respuesta .= balance_general_activo_corriente($id_actual, $id_anterior);
	$respuesta .= balance_general_respuesta_lplazo('INVERSIONES A LARGO PLAZO', '12', '1', '999',$id_actual, $id_anterior);
	$respuesta .= balance_general_respuesta_lplazo('DEUDORES A LARGO PLAZO', '13', '2', '999', $id_actual, $id_anterior);
	
	$respuesta .= balance_general_respuesta_lplazo('PROPIEDADES PLANTA Y EQUIPO', '15', '4', '092', $id_actual, $id_anterior);
	$respuesta .= balance_general_respuesta_otros('Costo propiedades planta y equipo', array('1504', '1508', '1516', '1524', '1528', '1540'), $id_actual, $id_anterior);
	$respuesta .= balance_general_respuesta('Depreciacion acumulada', '1592', $id_actual, $id_anterior);
	/*****NO APLICA*****/
	//$respuesta .= balance_general_respuesta('Depreciacion diferida', '1596', $id_actual, $id_anterior);
	$respuesta .= balance_general_respuesta_lplazo('INTANGIBLES', '16', '4', '093', $id_actual, $id_anterior);
	$respuesta .= balance_general_respuesta_lplazo('DIFERIDOS', '17', '3', '999', $id_actual, $id_anterior);
	$respuesta .= balance_general_respuesta_lplazo('OTROS ACTIVOS', '18', '4', '999', $id_actual, $id_anterior);
	$respuesta .= balance_general_respuesta('TOTAL VALORIZACIONES', '19', $id_actual, $id_anterior);
	$respuesta .= balance_general_respuesta('Valoriz. de inversiones', '1905', $id_actual, $id_anterior);
	$respuesta .= balance_general_respuesta('Valoriz. de propied planta y equipo', '1910', $id_actual, $id_anterior);
	/******NO APLICA*******/
	//$respuesta .= balance_general_respuesta('Valoriz. otros activos', '1995', $id_actual, $id_anterior);
	$respuesta .= balance_general_activo_largo_plazo($id_actual, $id_anterior);
	
	 
	$respuesta .= balance_general_respuesta('TOTAL ACTIVO', '1', $id_actual, $id_anterior);
	$respuesta .= balance_general_respuesta('DEUDORES CONTROL', '83', $id_actual, $id_anterior);
	$respuesta .= balance_general_respuesta('RESPONSABILIDADES CONTINGENTES', '91', $id_actual, $id_anterior);
	$respuesta .= balance_general_mostrar_otras_cuentas($id_actual, $id_anterior);
	/****NO APLICA******/
	//$respuesta .= balance_general_respuesta('ORDEN ACREEDORAS ', '9395', $id_actual, $id_anterior);

	$respuesta .= '</div>';
	
	return $respuesta;
}

function balance_general_resta_otras_cuentas($fecha) {
	$cuenta81 = db_query('SELECT est_valor_reportado, field_codigo_puc_value 
		FROM estados_financieros, field_data_field_codigo_puc 
		WHERE est_entity_id = entity_id AND est_id_fecha = ' . $fecha . ' AND field_codigo_puc_value = 81');
	if ($cuenta81 != NULL) {
		$cuenta81 = $cuenta81->fetchAssoc();
		$cuenta81 = $cuenta81['est_valor_reportado'];
	}
	$cuenta82 = db_query('SELECT est_valor_reportado, field_codigo_puc_value 
		FROM estados_financieros, field_data_field_codigo_puc 
		WHERE est_entity_id = entity_id AND est_id_fecha = ' . $fecha . ' AND field_codigo_puc_value = 82');
	if ($cuenta82 != NULL) {
		$cuenta82 = $cuenta82->fetchAssoc();
		$cuenta82 = $cuenta82['est_valor_reportado'];
	}
	return $cuenta81+$cuenta82;
}

function balance_general_mostrar_otras_cuentas($id_actual, $id_anterior) {
	$res = '';	
	$res .= '
				<div class = "codigo nivel_3">
				<div class = "column_1 ">' . t('OTRAS CUENTAS ORDEN DEUDORAS') . '</div>
				<div class = "column_2 ">'.formato_millones2(balance_general_resta_otras_cuentas($id_actual)).'</div>
				<div class = "column_3 ">'.formato_millones2(balance_general_resta_otras_cuentas($id_anterior)).'</div>
				</div>';
	return $res;
}

function balance_general_operacion_total_activo_largo_plazo($fecha) {
	//Cuenta 100000  menos Sumatoria ( cuenta 110000  + anexo 142 Unid de Capt 01 reglon 999+unid de 
	//capt 02 reglon 999 +unidad de capt 03 reglon 999+ capt 04 reglones 999+091+092+093)
	$cuenta1 = db_query('SELECT est_valor_reportado, field_codigo_puc_value 
		FROM estados_financieros, field_data_field_codigo_puc 
		WHERE est_entity_id = entity_id AND est_id_fecha = ' . $fecha . ' AND field_codigo_puc_value = 1');
	if ($cuenta1 != NULL) {
		$cuenta1 = $cuenta1->fetchAssoc();
		$cuenta1 = $cuenta1['est_valor_reportado'];
	}
	$cuenta11 = db_query('SELECT est_valor_reportado, field_codigo_puc_value 
		FROM estados_financieros, field_data_field_codigo_puc 
		WHERE est_entity_id = entity_id AND est_id_fecha = ' . $fecha . ' AND field_codigo_puc_value = 11');
	if ($cuenta11 != NULL) {
		$cuenta11 = $cuenta11->fetchAssoc();
		$cuenta11 = $cuenta11['est_valor_reportado'];
	}
	$sum_anexos = balance_general_sumas_app('1', array('999'), $fecha)+balance_general_sumas_app('2', array('999'), $fecha)+
	balance_general_sumas_app('3', array('999'), $fecha)+balance_general_sumas_app('4', array('999', '091', '092', '093'), $fecha);
	return $cuenta1-($sum_anexos+$cuenta11);
}

function balance_general_activo_largo_plazo($id_actual, $id_anterior) {
	$res = '';	
	$res .= '
				<div class = "codigo nivel_3">
				<div class = "column_1 ">' . t('TOTAL ACTIVO LARGO PLAZO') . '</div>
				<div class = "column_2 ">'.formato_millones2(balance_general_operacion_total_activo_largo_plazo($id_actual)).'</div>
				<div class = "column_3 ">'.formato_millones2(balance_general_operacion_total_activo_largo_plazo($id_anterior)).'</div>
				</div>';
	return $res;
}


function balance_general_respuesta($name, $cod, $id_actual, $id_anterior) {
	$res = '';
	
	$valor_actual = balance_general_query($id_actual, $cod);
	$valor_anterior = balance_general_query($id_anterior, $cod);
	if ($valor_actual == 0 && $valor_anterior == 0) return '';
        
        //$id=12-> diciembre 31 del 2012
        if( $id_actual==12 && $cod == 331595 ) {
            $valor_actual = 468863.63*1000000;
        }
        if( $id_anterior==12 && $cod == 331595 ) {
            $valor_anterior = 468863.63*1000000;
        }

        //$id=12-> diciembre 31 del 2012
        if( $id_actual==14 && $cod == 331595 ) {
            $valor_actual = 476705.06*1000000;
        }
        if( $id_anterior==14 && $cod == 331595 ) {
            $valor_anterior = 476705.06*1000000;
        }

        //$id=15-> septiembre del 2013
        if( $id_actual==15 && $cod == 331595 ) {
            $valor_actual = 476705.06*1000000;
        }
        if( $id_anterior==15 && $cod == 331595 ) {
            $valor_anterior = 476705.06*1000000;
        }

        
	
	if ($cod == '1592' || $cod == '37') {
		$res .= '
				<div class = "codigo nivel_3">
				<div class = "column_1 ">' . $name . '</div>
				<div class = "column_2 ">-'.formato_millones2($valor_actual).'</div>
				<div class = "column_3 ">-'.formato_millones2($valor_anterior).'</div>
				</div>';
		return $res;
	}
	$res .= '
				<div class = "codigo nivel_3">
				<div class = "column_1 ">' . $name . '</div>
				<div class = "column_2 ">'.formato_millones2($valor_actual).'</div>
				<div class = "column_3 ">'.formato_millones2($valor_anterior).'</div>
				</div>';
		return $res;
}

function balance_general_respuesta_lplazo($name, $cod, $app, $cod_renglon, $id_actual, $id_anterior) {
	$sum_actual = round(balance_general_query($id_actual, $cod))-round(balance_general_query_app($id_actual, $app, $cod_renglon)); 
	$sum_anterior = round(balance_general_query($id_anterior, $cod))-round(balance_general_query_app($id_anterior, $app, $cod_renglon));
	
	if ($sum_actual == 0 && $sum_anterior == 0) return '';
	
	$res = '';	
	$res .= '
				<div class = "codigo nivel_3">
				<div class = "column_1 ">' . t($name) . '</div>
				<div class = "column_2 ">'.formato_millones2($sum_actual).'</div>
				<div class = "column_3 ">'.formato_millones2($sum_anterior).'</div>
				</div>';
	return $res;
}

function balance_general_respuesta_otros($name, $cod, $id_actual, $id_anterior) {
	$sum_actual = 0; 
	$sum_anterior = 0; 
	foreach ($cod as $key => $value) {
		$sum_actual = $sum_actual + round(balance_general_query($id_actual, $value));
		$sum_anterior = $sum_anterior + round(balance_general_query($id_anterior, $value));
	}
	$res = '';	
	$res .= '
				<div class = "codigo nivel_3">
				<div class = "column_1 ">' . t($name) . '</div>
				<div class = "column_2 ">'.formato_millones2($sum_actual).'</div>
				<div class = "column_3 ">'.formato_millones2($sum_anterior).'</div>
				</div>';
	return $res;
}

function balance_general_respuesta_otros2($name, $unidad ,$cod, $id_actual, $id_anterior) {
	$sum_actual = 0; 
	$sum_anterior = 0; 
	foreach ($cod as $key => $value) {
		$sum_actual = $sum_actual + round(balance_general_query_app($id_actual, $unidad, $value));
		$sum_anterior = $sum_anterior + round(balance_general_query_app($id_anterior, $unidad, $value));
	}
	$res = '';	
	$res .= '
				<div class = "codigo nivel_3">
				<div class = "column_1 ">' . t($name) . '</div>
				<div class = "column_2 ">'.formato_millones2($sum_actual).'</div>
				<div class = "column_3 ">'.formato_millones2($sum_anterior).'</div>
				</div>';
	return $res;
}

function balance_general_sumas_app($unidad ,$cod, $fecha) {
	$sum_actual = 0; 
	foreach ($cod as $key => $value) {
		$sum_actual = $sum_actual + round(balance_general_query_app($fecha, $unidad, $value));
	}
	return $sum_actual;
}
/**
 * function Activo corrienter
 */
function balance_general_total_activo_corriente($fecha) {
	$cuenta11 = db_query('SELECT est_valor_reportado, field_codigo_puc_value 
		FROM estados_financieros, field_data_field_codigo_puc 
		WHERE est_entity_id = entity_id AND est_id_fecha = ' . $fecha . ' AND field_codigo_puc_value = 11');
	if ($cuenta11 != NULL) {
		$cuenta11 = $cuenta11->fetchAssoc();
		$cuenta11 = $cuenta11['est_valor_reportado'];
	}
	$sum_anexos = balance_general_sumas_app('1', array('999'), $fecha)+balance_general_sumas_app('2', array('999'), $fecha)+
	balance_general_sumas_app('3', array('999'), $fecha)+balance_general_sumas_app('4', array('999', '091', '092', '093'), $fecha);
	return $sum_anexos+$cuenta11;
}

function balance_general_activo_corriente($id_actual, $id_anterior) {
	$res = '';	
	$res .= '
				<div class = "codigo nivel_3">
				<div class = "column_1 ">' . t('TOTAL ACTIVO CORRIENTE') . '</div>
				<div class = "column_2 ">'.formato_millones2(balance_general_total_activo_corriente($id_actual)).'</div>
				<div class = "column_3 ">'.formato_millones2(balance_general_total_activo_corriente($id_anterior)).'</div>
				</div>';
	return $res;
}

function balance_general_respuesta_app($name, $cod, $cod_renglon, $id_actual, $id_anterior) {
    
        $valor_actual = balance_general_query_app($id_actual, $cod, $cod_renglon);
	$valor_anterior = balance_general_query_app($id_anterior, $cod, $cod_renglon);
	if ($valor_actual == 0 && $valor_anterior == 0) return '';

	$res = '';	
	$res .= '
				<div class = "codigo nivel_3">
				<div class = "column_1 ">' . t($name) . '</div>
				<div class = "column_2 ">'.formato_millones2($valor_actual).'</div>
				<div class = "column_3 ">'.formato_millones2($valor_anterior).'</div>
				</div>';
	return $res;
}

function formato_millones2($valor) {
	$valor = round($valor);
	$valor = $valor/1000000;
	$valor = number_format ($valor, 2, ',', '.');
	return $valor;
}

function balance_general_query_app($fecha, $cod, $cod_renglon) {
	
        $query = db_query('
		SELECT app_01 
		FROM activos_pasivos_patrimonio 
		WHERE app_fecha = '.$fecha.' AND app_renglon = '. $cod_renglon .' AND app_orden = '. $cod);
	
	if ($query != NULL) {
		$query = $query->fetchAssoc();
		return $query['app_01'];
	} else {
		return .00;
	} 
                
}

function balance_general_query($fecha, $cod) {
	$query = db_query('
		SELECT est_valor_reportado, field_codigo_puc_value 
		FROM estados_financieros, field_data_field_codigo_puc 
		WHERE est_entity_id = entity_id AND est_id_fecha = ' . $fecha . ' AND field_codigo_puc_value = '.$cod);
	if ($query != NULL) {
		$query = $query->fetchAssoc();
		return $query['est_valor_reportado'];
	} else {
		return .00;
	}
}

//consulta el puc segun la fecha
function consulta($puc, $id_fecha) {
	$res = db_query('
		SELECT est_entity_id, est_valor_reportado, field_codigo_puc_value
			FROM field_data_field_codigo_puc, estados_financieros
			WHERE	field_codigo_puc_value = '.$puc.' 
			AND entity_id = est_entity_id 
			AND est_id_fecha = ' .$id_fecha
	);
	if ($res != NULL) {
		foreach ($res as $key => $value) {
			return $value;
		}	
	} 
	else {
		return NULL;
	}
}


function construir_presentacion($id_actual, $id_anterior) {
	$res = 'entro';
	return $res; 
}

/*
*	 function form
*/
function valorem_balance_general_form($form, &$form_state) {
	$trimestre_actual = trimestre_actual();
	$ids = explode(',', $trimestre_actual);
	$id_anterior = $ids[0];
	$id_actual = isset($ids[1]) ? $ids[1] : 0;
	$form['periodo1'] = array(
    //'#title' => t('Periodo'),
    '#type' => 'select',
    '#options' => periodos3(),
    '#default_value' => isset ($_GET['id_periodo1']) ? $_GET['id_periodo1'] : $id_actual,
    '#weight' => -4,
  );
	$form['periodo2'] = array(
    //'#title' => t('Periodo'),
    '#type' => 'select',
    '#options' => periodos3(),
    '#default_value' => isset ($_GET['id_periodo2']) ? $_GET['id_periodo2'] : $id_anterior,
    '#weight' => -3,
  );
	$form['submit'] = array(
			'#type' => 'submit', 
			'#value' => t('Consultar')
	);
  return $form;
}

function valorem_balance_general_form_validate($form, &$form_state) {
	$actual = $form_state['values']['periodo1'];
	$anterior = $form_state['values']['periodo2'];
	if (($actual == 'Periodo') && ($anterior == 'Periodo')) {
		form_set_error('periodo1', 'Seleccione Periodo');
		form_set_error('periodo2', 'Seleccione Periodo');
	} else {
		if (($actual == 'Periodo') || ($anterior == 'Periodo')) {	
		}	else {
			$str_fecha = consultar_id_fecha($actual);
			$fecha_act = formatear_fecha($str_fecha);
			$str_fecha = consultar_id_fecha($anterior);
			$fecha_ant = formatear_fecha($str_fecha);
			if ($fecha_act == $fecha_ant) {
				form_set_error('periodo1', 'Periodos iguales');
				form_set_error('periodo2', 'Seleccione dos Periodos diferetes');
			}
		}
	}
}

function valorem_balance_general_form_submit($form, &$form_state) {
	$actual = $form_state['values']['periodo1'];
	$anterior = $form_state['values']['periodo2'];
	//if (isset ($_GET['id_periodo1']) && isset ($_GET['id_periodo2'])) {
	$form_state['redirect'] = array('node/26', array(
		'query' => array('id_periodo1'=>$actual, 'id_periodo2'=>$anterior)));
}
/****************************************/

/**
 *  function  balance_general_listado
 */
function valorem_balance_general_listado_dos() {
  $id_anterior = 0;
	$id_actual = 0;
	if (isset ($_GET['id_periodo1']) && isset ($_GET['id_periodo2'])) {
		return construir_consulta_dos($_GET['id_periodo1'], $_GET['id_periodo2']);
	} else {
		$trimestre_actual = trimestre_actual();
		$ids = explode(',', $trimestre_actual);
		$id_anterior = $ids[0];
		$id_actual = isset($ids[1]) ? $ids[1] : 0;
		return construir_consulta_dos($id_actual, $id_anterior);
	}
}


function construir_consulta_dos($id_actual, $id_anterior) {
	$respuesta = array();
	$respuesta = '<div class = "balance_general table-type-A column_count_3">';
	$respuesta .= '<div class = "title">
		<div class = "column_1">Nombre</div>
		<div class = "column_2">'.formato_fecha($id_actual).'</div>
		<div class = "column_3">'.formato_fecha($id_anterior).'</div>
		</div>';
	$respuesta .= balance_general_respuesta_app(t('OBLIGACIONES FINANCIERAS'), '5', '999', $id_actual, $id_anterior);
	$respuesta .= balance_general_respuesta_resta('Obligaciones moneda legal', '7', '999', '020', $id_actual, $id_anterior);
	$respuesta .= balance_general_respuesta_app('Obligaciones moneda extranjera', '5', '020', $id_actual, $id_anterior);
	$respuesta .= balance_general_respuesta_app(t('PROVEEDORES'), '6', '999', $id_actual, $id_anterior);
	$respuesta .= balance_general_respuesta_app(t('CUENTAS POR PAGAR'), '7', '999', $id_actual, $id_anterior);
	$respuesta .= balance_general_respuesta_app(t('A casa matriz'), '7', '020', $id_actual, $id_anterior);
	$respuesta .= balance_general_respuesta_app(t('A companias vinculadas'), '7', '030', $id_actual, $id_anterior);
	$respuesta .= balance_general_respuesta_app(t('A contratistas'), '7', '040', $id_actual, $id_anterior);
	$respuesta .= balance_general_respuesta_app(t('Deudas con socios y accionista'), '7', '100', $id_actual, $id_anterior);
	$respuesta .= balance_general_respuesta_app(t('Dividendos y participaciones'), '7', '120', $id_actual, $id_anterior);
	$respuesta .= balance_general_respuesta_app(t('Iva Retenido'), '7', '140', $id_actual, $id_anterior);	
	$respuesta .= balance_general_respuesta_app(t('Impuesto de Ind. y Comercio'), '7', '150', $id_actual, $id_anterior);
	//$respuesta .= balance_general_respuesta(t('Otras cuentas por pagar', '2367', $id_actual, $id_anterior);+010+050+070+080+090+110+130+160+170+180
	$respuesta .= balance_general_respuesta_otros2('Otras cuentas por pagar', '7', array('010', '050', '060', '070', '080', '090', '110', '130', '160','170', '180'), $id_actual, $id_anterior);
	
	$respuesta .= balance_general_respuesta_app(t('IMPUESTOS GRAVAMENES'), '8', '999', $id_actual, $id_anterior);
	$respuesta .= balance_general_respuesta_app(t('OBLIGACIONES LABORALES'), '9', '999', $id_actual, $id_anterior);
	$respuesta .= balance_general_respuesta_app(t('PASIVOS ESTIMADOS'), '10', '999', $id_actual, $id_anterior);
	$respuesta .= balance_general_respuesta_app(t('DIFERIDOS'), '11', '999', $id_actual, $id_anterior);
	$respuesta .= balance_general_respuesta_app(t('OTROS PASIVOS'), '12', '999', $id_actual, $id_anterior);
	$respuesta .= balance_general_respuesta_app(t('BONOS Y PAPELES COMERCIALES'), '13', '999', $id_actual, $id_anterior);
	
	$respuesta .= balance_general_pasivo_corriente($id_actual, $id_anterior);
	$respuesta .= balance_general_respuesta_lplazo(t('OBLIGACIONES FINANCIERAS'), '21' , '05', '999', $id_actual, $id_anterior);
	//$respuesta .= balance_general_obligaciones_moneda_legal($id_actual, $id_anterior);
	//$respuesta .= balance_general_respuesta(t('Obligaciones moneda legal'), '2105', $id_actual, $id_anterior);
	$respuesta .= balance_general_respuesta_lplazo(t('Obligaciones moneda extranjera'), '2110', '5', '020', $id_actual, $id_anterior);
	$respuesta .= balance_general_respuesta_lplazo(t('PROVEEDORES'), '22', '6', '999', $id_actual, $id_anterior);
	$respuesta .= balance_general_respuesta_lplazo(t('CUENTAS POR PAGAR'), '23', '7', '999', $id_actual, $id_anterior);
	$respuesta .= balance_general_respuesta_lplazo(t('OBLIGACIONES LABORALES'), '25', '9', '999', $id_actual, $id_anterior);
	$respuesta .= balance_general_respuesta_lplazo(t('PASIVOS ESTIMADOS Y PROVISIONE'), '26', '10', '999', $id_actual, $id_anterior);
	$respuesta .= balance_general_respuesta_lplazo(t('DIFERIDOS'), '27', '11', '999', $id_actual, $id_anterior);
	$respuesta .= balance_general_respuesta_lplazo(t('OTROS PASIVOS'), '28', '12', '999', $id_actual, $id_anterior);
	$respuesta .= balance_general_respuesta_lplazo(t('BONOS Y PAPELES COMERCIALES'), '29', '13', '999', $id_actual, $id_anterior);
	$respuesta .= balance_general_respuesta_lplazo('IMPUESTOS', '24', '8', '999', $id_actual, $id_anterior);
	$respuesta .= balance_general_pasivo_no_corriente($id_actual, $id_anterior);
	$respuesta .= balance_general_respuesta(t('TOTAL PASIVO'), '2', $id_actual, $id_anterior);
	$respuesta .= balance_general_respuesta(t('CAPITAL SOCIA'), '31', $id_actual, $id_anterior);
	$respuesta .= balance_general_respuesta(t('SUPERAVIT DE CAPITAL'), '32', $id_actual, $id_anterior);
	$respuesta .= balance_general_respuesta(t('Prima en colocacion de accione'), '3205', $id_actual, $id_anterior);
	/**** NO APLICA ******/
	//$respuesta .= balance_general_respuesta('Otras', '2', $id_actual, $id_anterior);
	
	$respuesta .= balance_general_respuesta('Metodo de Participacion y Otra', '3225', $id_actual, $id_anterior); // 32-3205
	$respuesta .= balance_general_respuesta(t('RESERVAS'), '33', $id_actual, $id_anterior);
	$respuesta .= balance_general_respuesta(t('Obligatorias'), '3305', $id_actual, $id_anterior);
	$respuesta .= balance_general_respuesta(t('RESERVAS ESTATUTARIAS'), '3310', $id_actual, $id_anterior);
	$respuesta .= balance_general_respuesta(t('RESERVAS OCASIONALES'), '3315', $id_actual, $id_anterior);
	$respuesta .= balance_general_respuesta('Otras reservas', '331595', $id_actual, $id_anterior);  //3315-3310
	$respuesta .= balance_general_respuesta(t('REVALORIZACION DEL PATRIMONIO'), '34', $id_actual, $id_anterior);
	$respuesta .= balance_general_respuesta(t('DIVIDENDOS DECRETADOS EN ACCIO'), '3505', $id_actual, $id_anterior);
	$respuesta .= balance_general_respuesta(t('RESULTADOS DEL EJERCICIO'), '36', $id_actual, $id_anterior);
	$respuesta .= balance_general_respuesta(t('RESULTADOS EJERCICIOS ANTERIOR'), '37', $id_actual, $id_anterior);
	$respuesta .= balance_general_respuesta(t('SUPERAVIT POR VALORIZACIONES'), '38', $id_actual, $id_anterior);
	$respuesta .= balance_general_respuesta(t('TOTAL PATRIMONIO'), '3', $id_actual, $id_anterior);
	$respuesta .= balance_general_respuesta(t('TOTAL PASIVO Y PATRIMONIO'), '1', $id_actual, $id_anterior);
	$respuesta .= balance_general_respuesta(t('DEUDORAS CONTROL POR CONTRA'), '86', $id_actual, $id_anterior);
	$respuesta .= balance_general_respuesta(t('RESPONSABILIDADES POR CONTRA'), '94', $id_actual, $id_anterior);
	$respuesta .= balance_general_respuesta_otros('OTRAS ORDEN ACREEDORAS', array('84', '85'), $id_actual, $id_anterior);
	
/**
 * function Activo corrienter
 */	
	$respuesta .= '</div>';
	
	return $respuesta;
}

function balance_general_respuesta_resta($name, $unidad, $cod1, $cod2, $id_actual, $id_anterior) {

	$actual = round(balance_general_query_app($id_actual, $unidad, $cod1)) - round(balance_general_query_app($id_actual, $unidad, $cod2));
	$anterior = round(balance_general_query_app($id_anterior, $unidad, $cod1)) - round(balance_general_query_app($id_anterior, $unidad, $cod2));
	

		//Parche mientras se sube el verdader. Si es la fecha nueve, use este valor
		if($id_actual==9) {
			$actual = 26881.05*1000000;
		}
		if($id_anterior==9) {
			$anterior = 26881.05*1000000;
		}

    //12-> 2012/12/31
    //unidad:7, cod1:999, $cod2:020 -> Obligaciones moneda legal 124,858.74
    if($id_actual==12 && $unidad==7 && $cod1 ==999 && $cod2==20 ) {
			$actual = 124858.74*1000000;
		}
		if($id_anterior==12 && $unidad==7 && $cod1 ==999 && $cod2==20 ) {
			$anterior = 124858.74*1000000;
		}

		//14
		if($id_actual==14 && $unidad==7 && $cod1 ==999 && $cod2==20 ) {
			$actual = 146840.30*1000000;
		}
		if($id_anterior==14 && $unidad==7 && $cod1 ==999 && $cod2==20 ) {
			$anterior = 146840.30*1000000;
		}


		//15
		if($id_actual==15 && $unidad==7 && $cod1 ==999 && $cod2==20 ) {
			$actual = 159157.61*1000000;
		}
		if($id_anterior==15 && $unidad==7 && $cod1 ==999 && $cod2==20 ) {
			$anterior = 146840.30*1000000;
		}

                
                
                
	$res = '';
	$res .= '
				<div class = "codigo nivel_3">
				<div class = "column_1 ">' . t($name) . '</div>
				<div class = "column_2 ">'.formato_millones2($actual).'</div>
				<div class = "column_3 ">'.formato_millones2($anterior).'</div>
				</div>';
	return $res;
}

// Pasivo corriente
function balance_general_total_pasivo_corriente($fecha) {
	$sum_anexos = balance_general_sumas_app('5', array('999'), $fecha)+balance_general_sumas_app('6', array('999'), $fecha)+
	balance_general_sumas_app('7', array('999'), $fecha)+balance_general_sumas_app('8', array('999'), $fecha)+
	balance_general_sumas_app('9', array('999'), $fecha)+balance_general_sumas_app('10', array('999'), $fecha)+
	balance_general_sumas_app('11', array('999'), $fecha)+balance_general_sumas_app('12', array('999'), $fecha)+
	balance_general_sumas_app('13', array('999'), $fecha);
	return $sum_anexos;
}

function balance_general_pasivo_corriente($id_actual, $id_anterior) {
	$res = '';	
	$res .= '
				<div class = "codigo nivel_3">
				<div class = "column_1 ">' . t('TOTAL PASIVO CORRIENTE') . '</div>
				<div class = "column_2 ">'.formato_millones2(balance_general_total_pasivo_corriente($id_actual)).'</div>
				<div class = "column_3 ">'.formato_millones2(balance_general_total_pasivo_corriente($id_anterior)).'</div>
				</div>';
	return $res;
}

// Obligaciones moneda legal
function balance_general_operacion_total_operacion_obligaciones_moneda($fecha) {
	//Igual Cuenta puc 210500 menos (Anexo 142  Unid de Cap  05 reglon 999 menos Anexo 142 unidad de Cap 05 reglon 020)
	$cuenta2105 = db_query('SELECT est_valor_reportado, field_codigo_puc_value 
		FROM estados_financieros, field_data_field_codigo_puc 
		WHERE est_entity_id = entity_id AND est_id_fecha = ' . $fecha . ' AND field_codigo_puc_value = 2105');
	if ($cuenta2105 != NULL) {
		$cuenta2105 = $cuenta2105->fetchAssoc();
		$cuenta2105 = $cuenta2105['est_valor_reportado'];
	}
	$sum_anexos = balance_general_sumas_app('5', array('999', '020'), $fecha);
	return $cuenta2105-$sum_anexos;
}

function balance_general_obligaciones_moneda_legal($id_actual, $id_anterior) {
	$res = '';	
	$res .= '
				<div class = "codigo nivel_3">
				<div class = "column_1 ">' . t('Obligaciones moneda legal') . '</div>
				<div class = "column_2 ">'.formato_millones2(balance_general_operacion_total_operacion_obligaciones_moneda($id_actual)).'</div>
				<div class = "column_3 ">'.formato_millones2(balance_general_operacion_total_operacion_obligaciones_moneda($id_anterior)).'</div>
				</div>';
	return $res;
}

// pasivo no corriente
function balance_general_pasivo_no_corriente($id_actual, $id_anterior) {
	$res = '';	
	$res .= '
				<div class = "codigo nivel_3">
				<div class = "column_1 ">' . t('TOTAL PASIVO NO CORRIENTE') . '</div>
				<div class = "column_2 ">'.formato_millones2(balance_general_total_pasivo_no_corriente($id_actual)).'</div>
				<div class = "column_3 ">'.formato_millones2(balance_general_total_pasivo_no_corriente($id_anterior)).'</div>
				</div>';
	return $res;
}

function balance_general_total_pasivo_no_corriente($fecha) {
	$cuenta2 = db_query('SELECT est_valor_reportado, field_codigo_puc_value 
		FROM estados_financieros, field_data_field_codigo_puc 
		WHERE est_entity_id = entity_id AND est_id_fecha = ' . $fecha . ' AND field_codigo_puc_value = 2');
	if ($cuenta2 != NULL) {
		$cuenta2 = $cuenta2->fetchAssoc();
		$cuenta2 = $cuenta2['est_valor_reportado'];
	}
	$sum_anexos = balance_general_sumas_app('5', array('999'), $fecha)+balance_general_sumas_app('6', array('999'), $fecha)+
	balance_general_sumas_app('7', array('999'), $fecha)+balance_general_sumas_app('8', array('999'), $fecha)+
	balance_general_sumas_app('9', array('999'), $fecha)+balance_general_sumas_app('10', array('999'), $fecha)+
	balance_general_sumas_app('11', array('999'), $fecha)+balance_general_sumas_app('12', array('999'), $fecha)+
	balance_general_sumas_app('13', array('999'), $fecha);
	return $cuenta2-$sum_anexos;
}

//
function balance_general_ordenes_acreedoras($id_actual, $id_anterior) {
	$res = '';	
	$res .= '
				<div class = "codigo nivel_3">
				<div class = "column_1 ">' . t('OTRAS ORDEN ACREEDORAS') . '</div>
				<div class = "column_2 ">'.formato_millones2(balance_general_total_ordenes_acreedoras($id_actual)).'</div>
				<div class = "column_3 ">'.formato_millones2(balance_general_total_ordenes_acreedoras($id_anterior)).'</div>
				</div>';
	return $res;
}

function balance_general_total_ordenes_acreedoras($fecha) {
	$cuenta84 = db_query('SELECT est_valor_reportado, field_codigo_puc_value 
		FROM estados_financieros, field_data_field_codigo_puc 
		WHERE est_entity_id = entity_id AND est_id_fecha = ' . $fecha . ' AND field_codigo_puc_value = 2');
	if ($cuenta84 != NULL) {
		$cuenta84 = $cuenta84->fetchAssoc();
		$cuenta84 = $cuenta84['est_valor_reportado'];
	}
	$cuenta85 = db_query('SELECT est_valor_reportado, field_codigo_puc_value 
		FROM estados_financieros, field_data_field_codigo_puc 
		WHERE est_entity_id = entity_id AND est_id_fecha = ' . $fecha . ' AND field_codigo_puc_value = 2');
	if ($cuenta85 != NULL) {
		$cuenta85 = $cuenta85->fetchAssoc();
		$cuenta85 = $cuenta85['est_valor_reportado'];
	}
	return $cuenta84+$cuenta85;
}