<?php

function popupper_init() {
    $path = libraries_get_path('colorbox');
    drupal_add_js($path . "/jquery.colorbox-min.js", 'file');
    drupal_add_css($path . '/colorbox.css');
}

function popupper_menu() {
    $items['popupper'] = array(
        'title' => t('popupper'),
        'description' => t('atiende peticiones ajax del portal'),
        'type' => MENU_LOCAL_TASK,
        'page callback' => '_spfclean_view',
        'access arguments' => array('access content'),
        'weight' => 1,
    );
    return $items;
}

function _spfclean_view($pdf) {
    $pdf = $_GET['pdf'];
    $debug = isset($_GET['debug']) && $_GET['debug'] == 'on';
    $debug = true;
    $html = '';
    print $html;
    exit();
}

function popupper_theme($existing, $type, $theme, $path) {
    return array(
        'spdf' => array(
            'render element' => 'elements',
            'template' => 'spdf',
        ),
    );
}

?>