<?php
include(DRUPAL_ROOT . '/' . drupal_get_path('module', "custom_cron") ."/Excel/Classes/PHPExcel/IOFactory.php");
function custom_cron_cronapi($op, $job = NULL) {
  $items['get_mails'] = array(
    'description' => 'Get unit value',
    'rule' => '0 */3 * * *',
    'callback' => 'custom_cron_get_mails'
  );
  return $items;
}
function custom_cron_get_mails() {
  error_reporting(E_ALL);
  $objPHPExcel = PHPExcel_IOFactory::load("sites/default/files/Aceptacion.xlsx");
  $objPHPExcel->setActiveSheetIndex(0);
  $numRows = $objPHPExcel->setActiveSheetIndex(0)->getHighestRow();
 
  for ($i = 2; $i <= $numRows; $i++) {
      $mail = $objPHPExcel->getActiveSheet()->getCell('A'.$i)->getCalculatedValue();
      update_insert_unit($mail);
   }
}


/*********************** Funciones para Base de Datos *****************************/

function update_insert_unit($mail){
  $user = user_load_by_mail(trim($mail)); 
  $uid = $user->uid;
  $query = db_select('profile', 'p');
  $query->fields('p');
  $query->condition('p.uid', $uid, '=');
  $result = $query->execute();
  $count = 0;
  if (is_array($result) || is_object($result))
  {
  
    while ($row = $result->fetchAssoc()) {
      $query = db_select('field_data_field_autorizacion_datos_2015', 'a');
      $query->fields('a');
      $query->condition('a.entity_id', $row['pid'], '=');
      $result2 = $query->execute();
      $count = 0;
      if (is_array($result2) || is_object($result2))
      {
      
        while ($row2 = $result2->fetchAssoc()) {
          $count = $count + 1;
          dpm("ddd");
          db_update('field_data_field_autorizacion_datos_2015')
            ->fields(array(
                'field_data_field_autorizacion_datos_2015' => "1"
            ))
            ->condition('entity_id', $row['pid']  ,'=')        
            ->execute();
          db_update('field_revision_field_autorizacion_datos_2015')
            ->fields(array(
                'field_data_field_autorizacion_datos_2015' => "1"
            ))
            ->condition('entity_id', $row['pid']  ,'=')        
            ->execute();
          }

          if($count == 0){
            $nid = db_insert('field_data_field_autorizacion_datos_2015')
            ->fields(array(
              'entity_type' => "profile2",
              'bundle' => "periodista",
              'deleted' => "0",
              'entity_id' => $row['pid'],
              'revision_id' => $row['pid'],
              'language' => "und",
              'delta' => "0",
              'field_autorizacion_datos_2015_value'=> "1",
            ))
            ->execute();
             $nid = db_insert('field_revision_field_autorizacion_datos_2015')
            ->fields(array(
              'entity_type' => "profile2",
              'bundle' => "periodista",
              'deleted' => "0",
              'entity_id' => $row['pid'],
              'revision_id' => $row['pid'],
              'language' => "und",
              'delta' => "0",
              'field_autorizacion_datos_2015_value'=> "1",
            ))
            ->execute();
          }
          $count = 0;
      }
    }

  }
}







