<?php


/**
 *	Implementen hook_block_info
 **/
function valorem_activos_pasivos_corto_plazo_block_info() {
  $blocks = array();
  $blocks['info'] = array(
    'info' => t('block activos y pasivos corto plazo')
  );
	$blocks['info2'] = array(
    'info' => t('block Deudores por edades')
  );
  $blocks['info3'] = array(
    'info' => t('block Cuentas por pagar')
  );
  return $blocks;
}

/**
 * Implements hook_block_view
 */
function valorem_activos_pasivos_corto_plazo_block_view($delta = '') {
  $block = array();
	switch ($delta) {
  case 'info':
    $block['subject'] = '<p class = "title">' . t('ACTIVOS PASIVOS DE CORTO PLAZO') . '</p>'. drupal_render(drupal_get_form('valorem_activos_pasivos_corto_plazo_form'));
  	$block['content'] =  valorem_activos_pasivos_corto_plazo_page();
    break;
  case 'info2':
    $block['subject'] = '<p class = "title">' . t('DEUDORES POR EDADES') . '</p>'. drupal_render(drupal_get_form('valorem_deudores_por_edades_form'));
    $block['content'] =  valorem_deudores_por_edades_page();
    break;
  case 'info3':
    $block['subject'] = '<p class = "title">' . t('CUENTAS POR PAGAR POR EDADES') . '</p>'. drupal_render(drupal_get_form('valorem_cuentas_por_pagar_form'));
    $block['content'] =  valorem_cuentas_por_pagar_page();
    break;
  default:
    # code...
    break;
}
  
  return $block;
}

/**
 *
 */
function valorem_activos_pasivos_corto_plazo_page() {
	$id = 0;
	$res = '<div class = "act_pas_pat table-type-A column_count_2  notitle">';
  if (isset ($_GET['id_app'])) {
			$id = $_GET['id_app'];
	} 
	else {
		
		$id = trimestre_actual3();
		$id = $id['id'];
	}
	if ($id != 0) {
    $result = db_select('activos_pasivos_patrimonio', 'n')
    ->fields('n')
    ->condition('app_fecha', $id,'=')
    ->execute();
    $res .= ' <div class = "title">
    		<div class = "column_1">' . t('Descripción') . '</div>
    		<div class = "column_2">' . t('Valor') . '</div>
    	</div>';
    foreach ($result as $key => $value) {
      $res .= '<div class = "nivel_2">
      	<div class = "column_1">' . $value->app_descripcion . '</div>
        <div class = "column_2">' . number_format($value->app_01, 2, '.', ',') . '</div>
      </div>';
    }
    $res .= '</div>';
		return $res;
	}
	return t('No existen reportes') . '<br> ' . t('para cargar informe trimestral, presione') . ' <a href= "#">' . t('aquí') . '</a>';
}

function valorem_activos_pasivos_corto_plazo_form($form, &$form_state) {
		
	$trimestre_actual = trimestre_actual3();
	
	$form['periodo'] = array(
	    '#type' => 'select',
	    '#options' => periodos3(),
	    '#default_value' => isset ($_GET['id_app']) ? $_GET['id_app'] : $trimestre_actual,
	  );
		$form['submit'] = array(
			'#type' => 'submit', 
			'#value' => t('Consultar')
	);
  return $form;
}


/**
 *  Retorna un arreglo con las fechas existentes
 *  segun archivos almacenados
 */
function info_trimenstre() {
  $result = db_query('SELECT * FROM fecha ORDER BY fecha.fec_id_fecha DESC');
  $fechas = array();
  $ant = '';
  // agrupa por ano
  foreach ($result as $key => $value) {
    $formato_fecha = substr($value->fec_fecha, 0,2).'-'.substr($value->fec_fecha, 2,2).'-'.substr($value->fec_fecha, 4,4);
    if ($ant == substr($value->fec_fecha, 4,4)) {
      array_push($fechas[$ant], array($value->fec_fecha => $formato_fecha));
    } else {
      $fechas[substr($value->fec_fecha, 4,4)][] = array(
        $value->fec_fecha => $formato_fecha,
      );
      $ant = substr($value->fec_fecha, 4,4);
    }
  }
  // reajusta el arreglo
  $aux = array();
  $list_fecha = array();
  foreach ($fechas as $key => $value) {
    $aux = array();
    $cont = 1;
    foreach ($fechas[$key] as $key2 => $value) {
      //$aux[key($value)] = $value[key($value)];
      $aux[key($value)] = $cont.'° ' . t('Trimestre');
      $cont++;
    }
    $list_fecha[$key] = $aux;
  }
  return $list_fecha;
}

function valorem_activos_pasivos_corto_plazo_form_submit($form, &$form_state) {
  $trimestre_actual = trimestre_actual3();
	$id_fecha = $form_state['values']['periodo'];
	//dpm($trimestre_actual);
	$form_state['redirect'] = array('node/35', array('query' => array('id_app'=>$id_fecha, 'id_dpe'=>isset ($_GET['id_dpe']) ? $_GET['id_dpe'] : $trimestre_actual['id'], 'id_cue'=>isset ($_GET['id_cue']) ? $_GET['id_cue'] : $trimestre_actual['id'])));
}

//*** Deudores por edades  ****//

/**
 *
 */
function valorem_deudores_por_edades_page() {
  $id = 0;
  $res = '<div class = "deudores table-type-A column_count_5 notitle">';
  if (isset ($_GET['id_dpe'])) {
      $id = $_GET['id_dpe'];
  } 
  else {
    
    $id = trimestre_actual3();
    $id = $id['id'];
  }
  if ($id != 0) {
    $result = db_select('deudores_por_edades', 'n')
    ->fields('n')
    ->condition('deu_fecha', $id,'=')
    ->execute();
    $res .= '<div class = "title">
      	<div class = "column_1">' . t('Descripción') . '</div>
      	<div class = "column_2">' . t('Vigente') . '</div>
      	<div class = "column_3">' . t('Vencidas hasta 30 dias') . '</div>
      	<div class = "column_4">' . t('Vencidad desde 31 hasta a 360 dias') . '</div>
      	<div class = "column_5">' . t('Vencidas mas de 360 dias') . '</div>
      </div>';
    foreach ($result as $key => $value) {
      $res .= '<div class = "nivel_2">
	        <div class = "column_1">' . $value->deu_descripcion . '</div>
	        <div class = "column_2">' . number_format($value->deu_01, 2, '.', ',') . '</div>
	        <div class = "column_3">' . number_format($value->deu_02, 2, '.', ',') . '</div>
	        <div class = "column_4">' . number_format($value->deu_03, 2, '.', ',') . '</div>
	        <div class = "column_5">' . number_format($value->deu_04, 2, '.', ',') . '</div>
        </div>';
    }
    $res .= '</div>';
    return $res;
  }
  return t('No existen reportes') . ' <br> ' . t('para cargar informe trimestral, presione') . ' <a href= "#">' . t('aquí') . '</a>';
}

function valorem_deudores_por_edades_form($form, &$form_state) {
  $trimestre_actual = trimestre_actual3();
  
  $form['periodo'] = array(
      '#type' => 'select',
      '#options' => periodos3(),
      '#default_value' => isset ($_GET['id_dpe']) ? $_GET['id_dpe'] : $trimestre_actual,
    );
    $form['submit'] = array(
      '#type' => 'submit', 
      '#value' => t('Consultar')
  );
  return $form;
}

function valorem_deudores_por_edades_form_submit($form, &$form_state) {
  $trimestre_actual = trimestre_actual3();
	$trimestre_actual = $trimestre_actual['id'];
  $id_fecha = $form_state['values']['periodo'];
  $form_state['redirect'] = array('node/35', array(
    'query' => array(
    	'id_app'=>isset ($_GET['id_app']) ? $_GET['id_app'] : $trimestre_actual, 
    	'id_dpe'=>$id_fecha, 
    	'id_cue'=>isset ($_GET['id_cue']) ? $_GET['id_cue'] : $trimestre_actual)));		
}
 
 //** Cuentas por pagar por edades

function valorem_cuentas_por_pagar_page() {
  $id = 0;
  $res = '<div class = "cuentas table-type-A column_count_6 notitle">';
  if (isset ($_GET['id_cue'])) {
      $id = $_GET['id_cue'];
  } 
  else {
    
    $id = trimestre_actual3();
    $id = $id['id'];
  }
  if ($id != 0) {
    $result = db_select('cuentas_por_pagar', 'n')
    ->fields('n')
    ->condition('cue_fecha', $id,'=')
    ->execute();
    $res .= '<div class = "title">
      <div class = "column_1">' . t('Descripción') . '</div>
      <div class = "column_2">' . t('Vigente') . '</div>
      <div class = "column_3">' . t('Vencidas hasta 30 dias') . '</div>
      <div class = "column_4">' . t('Vencidad desde 31 hasta a 90 dias') . '</div>
      <div class = "column_5">' . t('Vencidad desde 91 hasta a 360 dias') . '</div>
      <div class = "column_6">' . t('Vencidas mas de 360 dias') . '</div></div>';
    foreach ($result as $key => $value) {
      $res .= '<div class = "nivel_2">
        <div class = "column_1">' . $value->cue_descripcion . '</div>
        <div class = "column_2">' . number_format($value->cue_01, 2, '.', ',') . '</div>
        <div class = "column_3">' . number_format($value->cue_02, 2, '.', ',') . '</div>
        <div class = "column_4">' . number_format($value->cue_03, 2, '.', ',') . '</div>
        <div class = "column_5">' . number_format($value->cue_04, 2, '.', ',') . '</div>
        <div class = "column_6">' . number_format($value->cue_04, 2, '.', ',') . '</div></div>';
    }
    $res .= '</div>';
    return $res;
  }
  return t('No existen reportes') . ' <br> ' . t('para cargar informe trimestral, presione') . ' <a href= "#">' . t('aquí') . '</a>';
}

function valorem_cuentas_por_pagar_form($form, &$form_state) {
  $trimestre_actual = trimestre_actual3();
	$trimestre_actual = $trimestre_actual['id'];
  $form['periodo'] = array(
      '#type' => 'select',
      '#options' => periodos3(),
      '#default_value' => isset ($_GET['id_cue']) ? $_GET['id_cue'] : $trimestre_actual,
    );
    $form['submit'] = array(
      '#type' => 'submit', 
      '#value' => t('Consultar')
  );
  return $form;
}

function valorem_cuentas_por_pagar_form_submit($form, &$form_state) {
  $trimestre_actual = trimestre_actual3();
  $id_fecha = $form_state['values']['periodo'];
  $form_state['redirect'] = array('node/35', array(
    'query' => array('id_app'=>isset ($_GET['id_app']) ? $_GET['id_app'] : $trimestre_actual, 'id_dpe'=>isset ($_GET['id_dpe']) ? $_GET['id_dpe'] : $trimestre_actual, 'id_cue'=>$id_fecha)));
}