<?php

/**
 * Implements hook_block_info
 */

function valorem_informacion_block_info() {
  $blocks = array();
  $blocks['info'] = array(
    'info' => t('Informacion')
  );
  return $blocks;
}

/**
 *  Implements hook_block_view
 */
function valorem_informacion_block_view($delta = '') {
  $block = array();
  $block['subject'] = t('CONTACTOS');
  $block['content'] = informacion_page();
  return $block;
}

/**
 *  function informacion_page
 */
 function informacion_page() {


    $output = '';
 
	$posicionIngles = strpos(request_uri(),'en-gb');
	$idioma = 'es';
    if ($posicionIngles>=0 && is_numeric($posicionIngles) ) {
      $idioma = 'en-gb';
    } else {
	  $idioma = 'es';
    }
 
	if($idioma=='es') {
		$node = node_load(63);  
		$node->title = '';
		$output = node_view($node);
	} else if($idioma=='en-gb') {
		$node = node_load(249);  
		$node->title = '';
		$output = node_view($node);
	}

    return $output;

 }




