<?php

/**
 * Implements hook_block_view_alter
 */

 
function valorem_link_menu_block_block_view_alter(&$data, $block) {
	//dpm($data);
	/*if (isset ($data['subject']) && $data['subject'] == 'Informacion Financiera') {
		$data['subject'] = l('Informacion Financiera', 'node/25');
	}
	if (isset ($data['subject']) && $data['subject'] == 'Sociedad') {
		$data['subject'] = l('Sociedad', 'node/32');
	}*/
}