<?php
/**
* @file
* Adds Profile 2 support to Profile Complete.
*/

/**
* Implements hook_complete_profile_controller() on behalf of profile2 module.
*/
function profile2_complete_profile_controller() {
  $info = array();
  $info['profile2'] = 'Profile2CompleteProfileController';
  return $info;
}

/**
 * Returns an array of user-editable profile types by machine name, even if the
 * a profile entity for that type do not yet exist. This can happen if a user
 * has access to a profile type but has not yet saved any field values.
 */
function profile2_complete_profile_user_editable_profiles($account) {
  $editable_profiles = array();
  foreach (profile2_get_types() as $type => $info) {
    if ($info->userCategory && profile2_category_access($account, $type)) {
      $editable_profiles[] = $type;
    }
  }
  return $editable_profiles;
}

/**
 * Returns a list of all profiles saved for a user merged with any user-editable
 * profiles that may or may not exist yet. If a profile does not exist yet, a
 * dummy placeholder is created in its place.
 *
 * @see profile2_complete_profile_user_editable_profiles().
 */
function profile2_complete_profile_load_editable_by_user($account) {
  $profiles = profile2_load_by_user($account);
  $editable_profiles = profile2_complete_profile_user_editable_profiles($account);
  foreach ($editable_profiles as $type) {
    if (!isset($profiles[$type])) {
      $profiles[$type] = profile2_create(array('type' => $type, 'uid' => $account->uid));
    }
  }
  return $profiles;
}
