<?php

/**
 *
 */
function consultar_id_fecha_3($id) {
  $fecha_query = db_query('select fec_fecha from fecha where fec_id_fecha = '.$id);
  foreach ($fecha_query as $key => $value) {
    return $value->fec_fecha;
  }
}

function formatear_fecha_3($str_fecha) {
  if (strlen($str_fecha) != 8) {
    $str_fecha = '0'.$str_fecha;
  }
  $dd = substr($str_fecha, 0,2);
  $mm = substr($str_fecha, 2,2);
  $yy = substr($str_fecha, 4,4);
  $fecha = date('Y/m/d', strtotime($yy.'-'.$mm.'-'.$dd));
  return $fecha;
}

/** Retorna el valor en miles de millones**/
function formato_millones($valor) {
	/*$valor = substr(round($valor), 0, -6);
	if ($valor != '') {
		$valor = number_format ($valor, 0, '', '.');	
	}*/
	$valor = round($valor);
	$valor = $valor/1000000;
	$valor = number_format ($valor, 0, ',', '.');
	return $valor;
}

function formato_porcentage($valor) {
	$valor = number_format ($valor, 2, ',', '');
	return $valor;
}

function periodos_indices_financieros() {
  $fechas_orden = arreglo_fechas_indices_financieros();
  $new_arreglo = array();
  $fecha_anterior = 0;
  $i = 0;
  foreach ($fechas_orden as $key => $value) {
    if ($fecha_anterior != substr($value['fecha'], 0,4)) {
      $i = 1;
    }
    $new_arreglo['-----  '.substr($value['fecha'], 0,4).'  -----']['P'.$i] = array(
      $value['id'] => $value['fecha'],
    );
    $i++;
    $fecha_anterior = substr($value['fecha'], 0,4);
  }
  return array(
    'Periodo' => 'Periodo',
    '' => $new_arreglo
  );
}

function arreglo_fechas_indices_financieros() {
  $query = db_query('select * from fecha');
  $str_fecha = '';
  $fechas_orden = array();
  foreach ($query as $key => $value) {
    $str_fecha = $value->fec_fecha;
    if (strlen($str_fecha) != 8) {
      $str_fecha = '0'.$str_fecha;
    } 
    $dd = substr($str_fecha, 0,2);
    $mm = substr($str_fecha, 2,2);
    $yy = substr($str_fecha, 4,4);
    $fecha = date('Y/m/d', strtotime($yy.'-'.$mm.'-'.$dd));
    $fechas_orden[$fecha] = array(
      'fecha' => $fecha,
      'id' => $value->fec_id_fecha,
    );
  }
  // ordena desde ano, mes , dia
  sort($fechas_orden);
  return $fechas_orden;
}

function trimestre_actual_indices_financieros() {
  $fechas = arreglo_fechas_indices_financieros();
  $cont = 0;
  foreach ($fechas as $value) {
    $cont++;
  }
  if ($cont == 1) {
    $ids = $fechas[$cont-1]['id'];  
  }
  else {
    $ant = $fechas[$cont-2];
    $act = $fechas[$cont-1];
    $ids = $ant['id'].','.$act['id'];
  }
  return $ids;
}

function periodos3() {
    $fechas_orden = arreglo_fechas3();
    $new_arreglo = array();
    $fecha_anterior = 0;
    $i = 0;
    foreach ($fechas_orden as $key => $value) {
      if ($fecha_anterior != substr($value['fecha'], 0,4)) {
        $i = 1;
      }
      $new_arreglo['-----  '.substr($value['fecha'], 0,4).'  -----']['P'.$i] = array(
        $value['id'] => $value['fecha'],
      );
      $i++;
      $fecha_anterior = substr($value['fecha'], 0,4);
    }
    return array(
      'Periodo' => 'Periodo',
      '' => $new_arreglo
    );
  }
  
  function arreglo_fechas3() {
  $query = db_query('select * from fecha');
  $str_fecha = '';
  $fechas_orden = array();
  foreach ($query as $key => $value) {
    $str_fecha = $value->fec_fecha;
    if (strlen($str_fecha) != 8) {
      $str_fecha = '0'.$str_fecha;
    } 
    $dd = substr($str_fecha, 0,2);
    $mm = substr($str_fecha, 2,2);
    $yy = substr($str_fecha, 4,4);
    $fecha = date('Y/m/d', strtotime($yy.'-'.$mm.'-'.$dd));
    $fechas_orden[$fecha] = array(
      'fecha' => $fecha,
      'id' => $value->fec_id_fecha,
    );
  }
  // ordena desde ano, mes , dia
  sort($fechas_orden);
  return $fechas_orden;
}

function trimestre_actual3() {
    $fechas = arreglo_fechas3();
    $cont = 0;
    foreach ($fechas as $value) {
      $cont++;
    }
    if ($cont == 1) {
      $id = $fechas[$cont-1]['id']; 
    }
    else {
      $id = $fechas[$cont-1];
    }
    return $id;
  }
  
// retorna la fecha formateada  
function formato_fecha($id) {
	$result = db_select('fecha', 'c')
    ->fields('c')
		->condition('fec_id_fecha', $id,'=')
    ->execute()
    ->fetchAssoc();
	$str_fecha = $result['fec_fecha'];
	if (strlen($str_fecha) != 8) {
		$str_fecha = '0'.$str_fecha;
	} 
	$dd = substr($str_fecha, 0,2);
  $mm = substr($str_fecha, 2,2);
	$yy = substr($str_fecha, 4,4);
	$fecha = date('Y/m/d', strtotime($yy.'-'.$mm.'-'.$dd));
	return $fecha;
}

function trimestre_actual() {
	$fechas = arreglo_fechas();
	$cont = 0;
	foreach ($fechas as $value) {
		$cont++;
	}
	if ($cont == 1) {
		$ids = $fechas[$cont-1]['id'];	
	}
	else {
		$ant = $fechas[$cont-2];
		$act = $fechas[$cont-1];
		$ids = $ant['id'].','.$act['id'];
	}
	return $ids;
}

function arreglo_fechas() {
	$query = db_query('select * from fecha');
	$str_fecha = '';
	$fechas_orden = array();
	foreach ($query as $key => $value) {
		$str_fecha = $value->fec_fecha;
		if (strlen($str_fecha) != 8) {
			$str_fecha = '0'.$str_fecha;
		} 
		$dd = substr($str_fecha, 0,2);
	  $mm = substr($str_fecha, 2,2);
		$yy = substr($str_fecha, 4,4);
		$fecha = date('Y/m/d', strtotime($yy.'-'.$mm.'-'.$dd));
		$fechas_orden[$fecha] = array(
			'fecha' => $fecha,
			'id' => $value->fec_id_fecha,
		);
	}
	// ordena desde ano, mes , dia
	sort($fechas_orden);
	return $fechas_orden;
}

function consultar_id_fecha($id) {
	$fecha_query = db_query('select fec_fecha from fecha where fec_id_fecha = '.$id);
	foreach ($fecha_query as $key => $value) {
		return $value->fec_fecha;
	}
}

function formatear_fecha($str_fecha) {
	if (strlen($str_fecha) != 8) {
		$str_fecha = '0'.$str_fecha;
	}
	$dd = substr($str_fecha, 0,2);
	$mm = substr($str_fecha, 2,2);
	$yy = substr($str_fecha, 4,4);
	$fecha = date('Y/m/d', strtotime($yy.'-'.$mm.'-'.$dd));
	return $fecha;
}