<?php

/**
 * Implements hook_block_info
 */

function valorem_dividendos_block_info() {
  $blocks = array();
  $blocks['info'] = array(
    'info' => t('Dividendos')
  );
  return $blocks;
}

/**
 *  Implements hook_block_view
 */
function valorem_dividendos_block_view($delta = '') {
  $block = array();
  $block['subject'] = t('DIVIDENDOS');
  $block['content'] = dividendos_page();
  return $block;
}

/**
 *  function dividendos_page
 */
 function dividendos_page() {
   $node = node_load(54);  
   $node->title = '';
   return node_view($node);
 }




