<?php


function valorem_mapa_sitio_permission() {
  return array(
    'mapa_sitio' => array(
      'title' => t('Mapa del Sitio'),
      'description' => t('Perform Organigrama'),
    ),
  );
}

/**
 * Implementation of hook_menu().
 */
function valorem_mapa_sitio_menu() {
  $items = array();
  $items['mapa_sitio'] = array(
    'title' => t('Mapa del Sitio'),
    'page callback' => 'valorem_mapa_sitio_page',
    'access arguments' => array('mapa_sitio'),
  );
  return $items;
}

/**
 * Implements hook_block_info
 */
function valorem_mapa_sitio_block_info() {
  $blocks = array();
  $blocks['info'] = array(
    'info' => t('Mapa del Sitio')
  );
  return $blocks;
}

/**
 * Implements hook_block_view
 */
function valorem_mapa_sitio_block_view($delta = '') {
  $block = array();
  $block['subject'] = t('MAPA DEL SITIO');
  $block['content'] =  valorem_mapa_sitio_new();
  //'<iframe src = "?q=mapa_sitio" class= "mapa_sitio" height="300px" width="100%" scrolling="no"></iframe>';
  return $block;
}

function valorem_mapa_sitio_new() {

	$posicionIngles = strpos(request_uri(),'en-gb');
	$idioma = 'es';
    if ($posicionIngles>=0 && is_numeric($posicionIngles) ) {
      $idioma = 'en-gb';
    } else {
	  $idioma = 'es';
    }


	$mapa_sitio = taxonomy_get_tree(10);
	$tid = '';
	$tid_array = array();
	foreach ($mapa_sitio as $key => $value) {
		if ($value->parents[0] == 0) {
			$tid = $value->tid;
		} else {
			if ($value->parents[0] == $tid) {
				$tid_array[$value->tid] = array(
					'name' => $value->name,
					'tid' => $value->tid,
				);
			}
		}
	}
	//dpm($tid_array);
	foreach ($tid_array as $key => $value) {
		//dpm(taxonomy_get_children($value['tid']));
	}
	return 'mapa sitio';
}

function valorem_mapa_sitio_page() {
	$mapa_sitio = taxonomy_get_tree(10);
	$i = 0;
  //drupal_add_js('http://www.google.com/jsapi', 'external');
  $res = '
    <script type="text/javascript" src="http://www.google.com/jsapi"></script>
    <script type="text/javascript">
    	google.load("visualization", "1", {packages: ["orgchart"]});
    </script>
    <script type="text/javascript">
    function drawVisualizationOR() {
      var data = new google.visualization.DataTable();
      data.addColumn("string", "Name");
      data.addColumn("string", "Manager");
      data.addColumn("string", "ToolTip");
      data.addRows('.count($mapa_sitio).');
      ';
      foreach ($mapa_sitio as $key => $value) {
      	$path = "'". $value->description . "' TARGET = 'blank'";
        if ($value->parents[0] == 0) {
        	$path = "'".isset($value->description) ? $value->description : "'#'" . "'";
          $res .= '
            data.setCell('.$i.', 0, "'.$value->name.'" ,"'.'<a href = '. "'#'" .'><div>'.$value->name.'</div></a>'.'");
            data.setCell('.$i.', 2, "' . $value->description . '");';
          } else {
            $padre = taxonomy_term_load($value->parents[0]); 
            $res .= '
              data.setCell('.$i.', 0, "'.$value->name.'", "'.'<a href = '. $path .'><div>'.$value->name.'</div></a>'.'");
              data.setCell('.$i.', 1, "'.$padre->name.'");
              data.setCell('.$i.', 2, "'.$value->description.'");
            ';
          }
        $i++;
      }
    $res .= '
      new google.visualization.OrgChart(document.getElementById("visualization_mapa_sitio")).
      draw(data, {allowHtml: true, allowCollapse: false});
    }       
    jQuery(document).ready(function() {       
      google.setOnLoadCallback(drawVisualizationOR);  
    });
			
    </script>
    <div id="visualization_mapa_sitio"></div>';
  return $res;
}

function valorem_mapa_sitio_css_alter(&$css) {
	$cp = current_path();
  if ($cp == 'mapa_sitio') {
  	$i = 1;
    foreach ($css as $key => $value) {
			unset($css[$key]);
    }
  }
}

function valorem_mapa_sitio_js_alter(&$javascript) {
  if (current_path() == 'mapa_sitio') {
    unset($javascript['sites/all/modules/contrib/admin_menu/admin_menu.js']['data']);
  }
}