<?php
/**
 * Implements hook_block_info
 */
function valorem_tickers_block_info() {
  $blocks = array();
  $blocks['info'] = array(
    'info' => t('Tickers')
  );
  return $blocks;
}

/**
 * Implements hook_block_view
 */
 function valorem_tickers_block_view($delta = '') {
   $block = array();
   $block['subject'] = '';
   $block['content'] =  tickers_page();
   return $block;
 }
 
 /**
  * Funtion tickers
  */
 function tickers_page() {
    //Componente flex: http://201.234.71.35/Emisores/Labtiked.html
    //Componente gif:  http://backdata.dataifx.com/tickers/tickerValorem.gif
    return '<iframe src = "http://widgetsdataifx.blob.core.windows.net/valorem/ticker" class= "ticket" height="22px" width="974px" scrolling="no"></iframe>';
 }