<?php

require_once 'ooyala_patches.ajax.inc';

function ooyala_patches_form_alter(&$form, &$form_state, $form_id) {
	if (isset($form['field_tipo_multimedia']))
		foreach ($form['field_tipo_multimedia']['und']['#options'] as $key => $value) {
			$pairs = explode(':', $value);
			$form['field_tipo_multimedia']['und']['#options'][$key] = $pairs[0];
		}

	if (isset($form['field_multimedia_proyectos']))
		foreach ($form['field_multimedia_proyectos']['und']['#options'] as $key => $value) {
			$pairs = explode(':', $value);
			$form['field_tipo_multimedia']['und']['#options'][$key] = $pairs[0];
		}

	$forms = array();
	
	switch ($form_id) {
		case 'recurso_node_form':
		case 'noticia_node_form':
		case 'quienes_somos_node_form':
		case 'blog_node_form':
		case 'iniciativa_node_form':
			drupal_add_js(drupal_get_path('module', 'ooyala_patches') . '/js/ooyala_patches.js', 'file');
			drupal_add_css('.form-item-field-video-und-0-value{display:none}', 'inline');
			drupal_add_css('#edit-field-full-multimedia-code-und-0-format{display:none}', 'inline');

			$forms[] = $form_id;

			$form['thumbnail']['#type'] = 'hidden';
			$form['#submit'][] = 'ooyala_multimedia_form_submit';

			$form['field_full_multimedia_code']['und'][0]['#format'] = 'php_code';
			break;
		case 'perfiles_caracol_node_form':

			drupal_add_js(drupal_get_path('module', 'ooyala_patches') . '/js/ooyala_patches.js', 'file');
			drupal_add_css('.form-item-field-video-und-0-value{display:none}', 'inline');
			drupal_add_css('#edit-field-full-multimedia-code-und-0-format{display:none}', 'inline');

			$forms[] = $form_id;

			$form['thumbnail']['#type'] = 'hidden';
			$form['#submit'][] = 'ooyala_multimedia_form_submit';

			$form['field_full_multimedia_code']['und'][0]['#format'] = 'php_code';
				dpm($form);
			break;
		case 'proyecto_node_form':
			drupal_add_js(drupal_get_path('module', 'ooyala_patches') . '/js/ooyala_patches.js', 'file');
			drupal_add_css('.form-item-field-video-proyect-und-0-value{display:none}', 'inline');
			drupal_add_css('#edit-field-video-proyectos-und-0-format--2{display:none}', 'inline');

			$forms[] = $form_id;

			$form['thumbnail']['#type'] = 'hidden';
			$form['#submit'][] = 'ooyala_multimedia_form_submit';

			$form['field_video_proyectos']['und'][0]['#format'] = 'php_code';
			break;
		case 'responsabilidad_social_contenido_node_form':

			drupal_add_js(drupal_get_path('module', 'ooyala_patches') . '/js/ooyala_patches.js', 'file');
			drupal_add_css('.form-item-field-video-und-0-value{display:none}', 'inline');
			drupal_add_css('#edit-field-full-multimedia-code-und-0-format{display:none}', 'inline');

			$forms[] = $form_id;

			$form['thumbnail']['#type'] = 'hidden';
			$form['#submit'][] = 'ooyala_multimedia_form_submit';			

			$form['field_full_multimedia_code']['und'][0]['#format'] = 'php_code';
			break;
	}
	drupal_add_js(array('ooyala_patches' => array('forms' => $forms)), 'setting');
}

function ooyala_multimedia_form_submit($form, &$form_state) {
	if (!empty($form_state['values']['thumbnail'])) {
		$fieldImage = isset($form['field_imagen']) ? 'field_imagen' : 'field_image';

		/* se elimina la imagen anterior */
		$toEraseFile = file_load($form_state['values'][$fieldImage]['und'][0]['fid']);
		if ($toEraseFile)
			file_delete($toEraseFile);

		/* se sube al servidor la nueva imagen y se registra */
		$file = system_retrieve_file($form_state['values']['thumbnail'], $form[$fieldImage]['und'][0]['#upload_location'], true, FILE_EXISTS_REPLACE);
		/* se asocia el nuevo archivo al nodo */
		$form_state['values'][$fieldImage]['und'][0]['fid'] = $file->fid;
	}
}