<?php

/**
 * Implements hook_block_info
 */

function valorem_administracion_links_block_info() {
  $blocks = array();
  $blocks['info1'] = array(
    'info' => t('Mapa del sitio')
  );
	$blocks['info2'] = array(
    'info' => t('Sitios de interés')
  );
  return $blocks;
}

/**
 *  Implements hook_block_view
 */
function valorem_administracion_links_block_view($delta = '') {
  switch ($delta) {
    case 'info1':
      $block = array();
  		$block['content'] = mapa_del_sitio();
      break;
    case 'info2':
      $block = array();
  		$block['content'] = sitios_de_interes();
      break;
    default:
      break;
  }
  return $block;
}

/**
 *  function Mapa del sitio
 */
 function mapa_del_sitio() {
 
	$output = '<div class = "mapa_sitio">'.l(t('Mapa del sitio'), 'sitemap').'</div>';
 
 
	$posicionIngles = strpos(request_uri(),'en-gb');
	$idioma = 'es';
    if ($posicionIngles>=0 && is_numeric($posicionIngles) ) {
      $idioma = 'en-gb';
    } else {
	  $idioma = 'es';
    }
	
	if($idioma == 'en-gb') {
		$output = '';
	}
 
   return $output;
 }
 
/**
 *  function Mapa del sitio
 */
 function sitios_de_interes() {
 	 drupal_add_js(drupal_get_path('module', 'valorem_administracion_links') . '/js/valorem_administracion_links.js', array('scope' => 'footer'));
   return '
   	<div class = "interes"><div class = "sitio_interes">'.l(t('Sitios de interes'), 'sitios-de-interes').'</div>'; 
	 	
 }
 
