<?php

/**
 * Implements hook_block_info
 */
function valorem_evolucion_activos_pasivos_patriomio_block_info() {
  $blocks = array();
  $blocks['info'] = array(
    'info' => t('Evolución activos - pasivos - patrimonio')
  );
  return $blocks;
}

/**
 * Implements hook_block_view
 */
function valorem_evolucion_activos_pasivos_patriomio_block_view($delta = '') {
  $block = array();
  $block['subject'] = "<p>" . t("INFORMACIÓN SOBRE RESULTADOS (Miles de Millones)") . "</p>";
  $block['content'] =  evolucion_activos_pasivos_patriomio_page();
 return $block;
}

function arreglo_fechas_ultimo() {
	$query = db_query('select * from fecha');
	$str_fecha = '';
	$fechas_orden = array();
	foreach ($query as $key => $value) {
		$str_fecha = $value->fec_fecha;
		if (strlen($str_fecha) != 8) {
			$str_fecha = '0'.$str_fecha;
		} 
		$dd = substr($str_fecha, 0,2);
	  $mm = substr($str_fecha, 2,2);
		$yy = substr($str_fecha, 4,4);
		$fecha = date('Y/m/d', strtotime($yy.'-'.$mm.'-'.$dd));
		$fechas_orden[$fecha] = array(
			'fecha' => $fecha,
			'id' => $value->fec_id_fecha,
		);
	}
	// ordena desde ano, mes , dia
	//arsort($fechas_orden);//oredena en oreden inverso
	return $fechas_orden;
}

function evolucion_activos_pasivos_patriomio_page() {
	$tabla_fechas = db_query('SELECT * FROM fecha ORDER BY fec_id_fecha ASC');
	if ($tabla_fechas != NULL) {
		$fechas = arreglo_fechas_ultimo();
		$i = 1;
		$estado_resultados = array();
		foreach ($fechas as $key => $value) {
			if ($i <= 8) {
				// 4  - Ingresos
				// 41 - Ingresos operacionales
				// 6  - costos de venta
				// 42 - Ingresos no aperacionales
				// 53 - Gastos no operacionales
				$respuesta = db_query('
					SELECT est_entity_id, est_valor_reportado, field_codigo_puc_value
					FROM field_data_field_codigo_puc, estados_financieros
					WHERE (
						field_codigo_puc_value = 4 OR 
						field_codigo_puc_value = 41 OR
						field_codigo_puc_value = 51 OR
						field_codigo_puc_value = 42 OR
						field_codigo_puc_value = 61 OR
						field_codigo_puc_value = 52 OR
						field_codigo_puc_value = 5160 OR
						field_codigo_puc_value = 5165 OR 
						field_codigo_puc_value = 53 OR
						field_codigo_puc_value = 59 OR
						field_codigo_puc_value = 6
					)
					AND entity_id = est_entity_id AND est_id_fecha =' .$value['id']
				);
				$ingresos_operacionales = 0;
				$costos = 0;
				$gastos_no_operacionales = 0;
				$ingresos_no_operacionales = 0;
				$gastos_no_operacionales = 0;
				$gastos_operacionales = 0;
				$costos = 0;
				$utilidad_bruta = 0;
				$admin = 0;
				$cuenta6 = 0;
				foreach ($respuesta as $key2 => $value2) {
					if ($value2->field_codigo_puc_value == 41) {
						$ingresos_operacionales = isset ($value2->est_valor_reportado) ? $value2->est_valor_reportado : 0;
					}
					if ($value2->field_codigo_puc_value == 61) {
						$costos = isset ($value2->est_valor_reportado) ? $value2->est_valor_reportado : 0;
					}
					if ($value2->field_codigo_puc_value == 52) {
						$gastos_operacionales = isset ($value2->est_valor_reportado) ? $value2->est_valor_reportado : 0;
					}
					if ($value2->field_codigo_puc_value == 42) {
						$ingresos_no_operacionales = isset ($value2->est_valor_reportado) ? $value2->est_valor_reportado : 0;
					}
					if ($value2->field_codigo_puc_value == 53) {
						$gastos_no_operacionales = isset ($value2->est_valor_reportado) ? $value2->est_valor_reportado : 0;
					}
					if ($value2->field_codigo_puc_value == 4) {
						$ingresos = isset ($value2->est_valor_reportado) ? $value2->est_valor_reportado : 0;
					}
					if ($value2->field_codigo_puc_value == 51) {
						$admin = isset ($value2->est_valor_reportado) ? $value2->est_valor_reportado : 0;
					}
					if ($value2->field_codigo_puc_value == 59) {
						$utilidad_neta = isset ($value2->est_valor_reportado) ? $value2->est_valor_reportado : 0;
					}
					if ($value2->field_codigo_puc_value == 6) {
						$cuenta6 = isset ($value2->est_valor_reportado) ? $value2->est_valor_reportado : 0;
					}
					/*'codigo' => $value2->field_codigo_puc_value,
					'codigo' => $value2->field_codigo_puc_value,
					'codigo' => $value2->field_codigo_puc_value,
					$valores_ebidta[$key] = $value2;*/
				}
				$utilidad_bruta = $ingresos_operacionales-$costos;
				//$unidad_neta = $utilidad_bruta-($admin+$gastos_no_operacionales); 
				//$ebidta = $ingresos_operacionales-($costos+$gastos_no_operacionales);
				$ebidta = $ingresos_operacionales-$cuenta6-$admin-$gastos_operacionales;
				$estado_resultados[] = array(
					'ingresos' => number_format (round($ingresos)/1000000000, 2, '.', ''),
					'ebidta' => number_format (round($ebidta)/1000000000, 2, '.', ''), 
					'unidad_neta' => number_format (round($utilidad_neta)/1000000000, 2, '.', ''),
					'fecha' => $value['fecha'],
				);
			}
			$i++;
		}
	  return grafica_estados_de_resultados($estado_resultados);
	  	
	} else {
		return t('no existen registros');
	}
	
}

	function grafica_estados_de_resultados($datos) {
		//arsort($datos);
		global $base_url;
		$res2 = '';
		foreach ($datos as $key => $value) {
			
			$res2 .= '["'.$value['fecha'].'", '.$value['ingresos'].','.$value['ebidta'].','.$value['unidad_neta'].'],';
		}
		$res2 = substr($res2, 0, -1);
		drupal_add_js('http://www.google.com/jsapi', 'external');
	  $res = '
	    <script type="text/javascript">
	    google.load("visualization", "1", {packages: ["corechart"]});
	    </script>
	    <script type="text/javascript">
	      function drawVisualizationER() {
	        var rowData = [
	          ["Trimestre", "Ingresos", "EBIDTA", "Utilidad Neta"],
	          '.$res2.'
	        ];
	        var data = google.visualization.arrayToDataTable(rowData);
          var ac = new google.visualization.ComboChart(document.getElementById("visualization"));
          ac.draw(data, {
            width: 620,
            height: 240,
            legend: {position: "top"},
            animation:{
              duration: 1000,
              easing: "in"
            },
            areaOpacity: 0.0,
            focusTarget: "category",
            fontSize: 14,
            hAxis: { 
              textPosition: "out", 
              textStyle: {color: "#999999", fontSize: 13}
            }, 
            tooltip: {
              textStyle: {color: "#999999", fontName: "arial", fontSize: 16}, 
              showColorCode: true, trigger:"hover"
            },
            chartArea: {
              left:45,top:35,width:"85%",height:"70%"
            },
            series: {
              0: {type: "bars", color: "#6189D8", areaOpacity: 0.0},
              1: {type: "line", color: "#ED1E79", visibleInLegend: true, targetAxisIndex:1, pointSize:4, lineWidth: 2}, 
              2: {type: "line", color: "#C29A16", visibleInLegend: true, targetAxisIndex:1, pointSize:4, lineWidth: 2}
            },
            vAxis: {
              baselineColor: "#C29A16", lineWidth: 6,direction: 1, 
              gridlines:{color: "#999999", count: 4}, textPosition: "out", 
              textStyle: {color: "#999999", fontName: "Arial", fontSize: 10}
            }                 
          });
	      }
	      jQuery(document).ready(function() {				
					google.setOnLoadCallback(drawVisualizationER);
				});
				
	    </script>
	  <div id="visualization"></div>';
		if (current_path() != 'node/25') {
			$res .= '<div class="ver_mas"><a href="' . $base_url . '/node/25">' . t('ver mas') . '</a></div>';
		} 
	  return $res;
	}