<?php

/**
 *	Implements hook_form_alter() 
 **/
function valorem_alter_login_form_alter(&$form, &$form_state, $form_id) {
	if ($form_id == 'user_login') {
		$form['contact_information'] = array(
  		'#markup' => '<div class texto-login>' . t('Para acceder porfavor ingrese con su nombre completo, APELLIDO(S) NOMBRE(S), y número de acciones hasta el 28 de Marzo de 2012. 
  		Si usted ingresa a nombre de una empresa, por favor digite el NIT correspondiente.') . '<p/><p/>' .
			t('Si usted tiene dudas con respecto al número de acciones de Valorem en su portafolio, por favor comuníquese con su Corredor de Bolsa.') . '</div>',
			'#weight' => -10,
		);
		$form['name']['#title'] = 'Nombre Completo o Nit';
		$form['pass']['#title'] = t('Numero de acciones');
		$form['pass']['#description'] = 'Escriba el numero de acciones correspondiente.';

                
            $form['#submit'][] = 'user_profile_form_redirect';
        
            $form_state['redirect'] = 'node/205';

	}
}

function user_profile_form_redirect($form, &$form_state) {
    
    $posicionIngles = strpos(request_uri(),'en-gb');
	$idioma = 'es';
    if ($posicionIngles>=0 && is_numeric($posicionIngles) ) {
      $idioma = 'en-gb';
    } else {
	  $idioma = 'es';
    }
    
    if($idioma == 'en-gb') {
		//$form_state['redirect'] = 'node/223';
        $form_state['redirect'] = 'live_streaming';
        
    } else {
		//$form_state['redirect'] = 'node/205';
        $form_state['redirect'] = 'live_streaming';
    }


  
}
