<?php
/**
 * Implements hook_block_info
 */
function valorem_indices_financieros_block_info() {
  $blocks = array();
  $blocks['info3'] = array(
    'info' => t('Indices Financieros')
  );
  return $blocks;
}

/**
 * Implements hook_block_view
 */
function valorem_indices_financieros_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'info3':
      $block['subject'] = '<p class = "title">' . t('INDICES FINANCIEROS') . '</p>' . drupal_render(drupal_get_form('valorem_indices_financieros_form'));
      $block['content'] = '<div  class = "nota-junta-up">' . l('super', 'http://superfinanciera.gov.co/web_valores/?MIval=Fechas_inf_fin&Tipo=066&Codigo=017&dibujo=simevcab.gif&titulo=Entidades%20Encontradas', array(
      	'attributes' => array(
      		'class' => 'super', 
      		'target'=>'_blank'
      	)
			))  . '  <div class = "millones">(' . t('Millones de pesos') . ') </div></div>' .  valorem_indices_financieros_page();
      break;
    default:
      # code...
      break;
  }
  return $block;
}

//** Indices financieros **/
function valorem_indices_financieros_page() {
  $id_anterior = 0;
  $id_actual = 0;
  if (isset ($_GET['id_periodos1']) && isset ($_GET['id_periodos2'])) {
    return valorem_indices_financieros_valores($_GET['id_periodos1'], $_GET['id_periodos2']);
  } else {
    $trimestre_actual = trimestre_actual();
    $ids = explode(',', $trimestre_actual);
    $id_anterior = $ids[0];
    $id_actual = isset($ids[1]) ? $ids[1] : 0;
    return valorem_indices_financieros_valores($id_actual, $id_anterior);
  }
}

/*
*  function form
*/
function valorem_indices_financieros_form($form, &$form_state) {
  $trimestre_actual = trimestre_actual_indices_financieros();
  $ids = explode(',', $trimestre_actual);
  $id_anterior = $ids[0];
  $id_actual = isset($ids[1]) ? $ids[1] : 0;
  $form['periodo1'] = array(
    //'#title' => t('Periodo'),
    '#type' => 'select',
    '#options' => periodos_indices_financieros(),
    '#default_value' => isset ($_GET['id_periodo1']) ? $_GET['id_periodo1'] : $id_actual,
    '#weight' => -4,
  );
  $form['periodo2'] = array(
    //'#title' => t('Periodo'),
    '#type' => 'select',
    '#options' => periodos_indices_financieros(),
    '#default_value' => isset ($_GET['id_periodo2']) ? $_GET['id_periodo2'] : $id_anterior,
    '#weight' => -3,
  );
  $form['submit'] = array(
    '#type' => 'submit', 
    '#value' => t('Consultar')
  );
  return $form;
}



function valorem_indices_financieros_form_validate($form, &$form_state) {
  $actual = $form_state['values']['periodo1'];
  $anterior = $form_state['values']['periodo2'];
  if (($actual == 'Periodo') && ($anterior == 'Periodo')) {
    form_set_error('periodo1', 'Seleccione Periodo');
    form_set_error('periodo2', 'Seleccione Periodo');
  } else {
    if (($actual == 'Periodo') || ($anterior == 'Periodo')) { 
    } else {
      $str_fecha = consultar_id_fecha_3($actual);
      $fecha_act = formatear_fecha_3($str_fecha);
      $str_fecha = consultar_id_fecha_3($anterior);
      $fecha_ant = formatear_fecha_3($str_fecha);
      if ($fecha_act == $fecha_ant) {
        form_set_error('periodo1', 'Periodos iguales');
        form_set_error('periodo2', 'Seleccione dos Periodos diferetes');
      }
    }
  }
}

function valorem_indices_financieros_form_submit($form, &$form_state) {
  $actual = $form_state['values']['periodo1'];
  $anterior = $form_state['values']['periodo2'];
  $form_state['redirect'] = array('node/28', array(
    'query' => array(
      'id_periodos1'=> isset ($actual) ? $actual : trimestre_actual_indices_financieros(), 
      'id_periodos2'=> isset ($anterior) ? $anterior : 0)));
}


function valorem_indices_financieros_valores($id_actual, $id_anterior) {
	$respuesta = array();
	$respuesta = '<div class = "balance_general table-type-A column_count_3">';
	$respuesta .= '<div class = "title">
		<div class = "column_1">Nombre</div>
		<div class = "column_2">'.formato_fecha($id_actual).'</div>
		<div class = "column_3">'.formato_fecha($id_anterior).'</div>
		</div>';
	$respuesta .= indices_financieros_dupont('. Rentabilidad del Activo o Dupont', $id_actual, $id_anterior);
	$respuesta .= indices_financieros_rentabilidad_patrimonio('Rentabilidad del patrimonio', $id_actual, $id_anterior);
	$respuesta .= indices_financieros_margen_operacional('Margen operacional', $id_actual, $id_anterior);
	$respuesta .= indices_financieros_margen_neto('Margen Neto', $id_actual, $id_anterior);
	$respuesta .= indices_financieros_razon_corriente('Razon corriente', $id_actual, $id_anterior);
	$respuesta .= indices_financieros_capital_trabajo('Capital de trabajo ', $id_actual, $id_anterior);
	$respuesta .= indices_financieros_endeudamiento('Concentracion endeudamiento a corto plazo', $id_actual, $id_anterior);
	$respuesta .= indices_financieros_endeudamiento_total('Endeudamiento total', $id_actual, $id_anterior);
	$respuesta .= indices_financieros_laverage_total('Laverage total', $id_actual, $id_anterior);
	$respuesta .= indices_financieros_rotacion('Rotacion de activos totales', $id_actual, $id_anterior);
	return $respuesta;
}

// Rentabilidad Dupont
//(cuenta 590000/cuenta 410000)*(cuenta 410000/cuenta 100000)*100
function indices_financieros_dupont($name, $id_actual, $id_anterior) {
	$res_act = (((indices_financieros_query($id_actual, '59')/indices_financieros_query($id_actual, '41'))*
	(indices_financieros_query($id_actual, '41')/indices_financieros_query($id_actual, '1'))))*100;
	$res_ant = (((indices_financieros_query($id_anterior, '59')/indices_financieros_query($id_anterior, '41'))*
	(indices_financieros_query($id_anterior, '41')/indices_financieros_query($id_anterior, '1'))))*100;
	$res = '';
	$res .= '
				<div class = "codigo nivel_3">
				<div class = "column_1 ">' . $name . '</div>
				<div class = "column_2 ">'.formato_porcentage($res_act).'</div>
				<div class = "column_3 ">'.formato_porcentage($res_ant).'</div>
				</div>';
		return $res;
}

// Rentabilidad del patrimonio 
//(cuenta 590000/cuenta 300000)*100
function indices_financieros_rentabilidad_patrimonio($name, $id_actual, $id_anterior) {
	$res_act = (indices_financieros_query($id_actual, '59')/indices_financieros_query($id_actual, '3'))*100;
	$res_ant = (indices_financieros_query($id_anterior, '59')/indices_financieros_query($id_anterior, '3'))*100;
	$res = '';
	$res .= '
				<div class = "codigo nivel_3">
				<div class = "column_1 ">' . $name . '</div>
				<div class = "column_2 ">'.formato_porcentage($res_act).'</div>
				<div class = "column_3 ">'.formato_porcentage($res_ant).'</div>
				</div>';
		return $res;
}

//Margen operacional
//=((cuenta 410000-cuenta 600000-cuenta 510000-cuenta 520000)/cuenta 410000)*100
function indices_financieros_margen_operacional($name, $id_actual, $id_anterior) {
	$res_act = ((indices_financieros_query($id_actual, '41')-indices_financieros_query($id_actual, '6')
	-indices_financieros_query($id_actual, '51')-indices_financieros_query($id_actual, '52'))
	/indices_financieros_query($id_actual, '41'))*100;
	
	$res_ant = ((indices_financieros_query($id_anterior, '41')-indices_financieros_query($id_anterior, '6')
	-indices_financieros_query($id_anterior, '51')-indices_financieros_query($id_anterior, '52'))
	/indices_financieros_query($id_anterior, '41'))*100;
	$res = '';
	$res .= '
				<div class = "codigo nivel_3">
				<div class = "column_1 ">' . $name . '</div>
				<div class = "column_2 ">'.formato_porcentage($res_act).'</div>
				<div class = "column_3 ">'.formato_porcentage($res_ant).'</div>
				</div>';
		return $res;
}

// Margen Neto
//(cuenta 590000/cuenta 410000)*100
function indices_financieros_margen_neto($name, $id_actual, $id_anterior) {
	$res_act = (indices_financieros_query($id_actual, '59')/indices_financieros_query($id_actual, '41'))*100;
	$res_ant = (indices_financieros_query($id_anterior, '59')/indices_financieros_query($id_anterior, '41'))*100;
		$res = '';
	$res .= '
				<div class = "codigo nivel_3">
				<div class = "column_1 ">' . $name . '</div>
				<div class = "column_2 ">'.formato_porcentage($res_act).'</div>
				<div class = "column_3 ">'.formato_porcentage($res_ant).'</div>
				</div>';
		return $res;
}

// Razon corriente
// (Cuenta 110000  + anexo 142 Unid de Capt 01 reglon 999+unid de capt 02 reglon 999 +
// unidad de capt 03 reglon 999+ Und capt 04 reglones 999+091+092+093)/
//( anexo 142 unid de cap 05 reglon 999 + 
//unid  de cap 06 reglon 999+ unid de cap 07 reglon 999+ unidad de Cap 08 reglon 999+unidad de cap 09 reglon 999+
// unidad de capt 10 reglon 999+unid de capt  11 reglon 999+ unid de capt 12 reglon 999 + unid  de cap 013 reglon 999)
function indices_financieros_razon_corriente($name, $id_actual, $id_anterior) {
	$res = '';
	$res .= '
				<div class = "codigo nivel_3">
				<div class = "column_1 ">' . $name . '</div>
				<div class = "column_2 ">'.formato_porcentage(indices_financieros_razon_corriente_operacion($id_actual)).'</div>
				<div class = "column_3 ">'.formato_porcentage(indices_financieros_razon_corriente_operacion($id_anterior)).'</div>
				</div>';
		return $res;
}

function indices_financieros_razon_corriente_operacion($fecha) {
	$anexo = (indices_financieros_query($fecha, '11')+indices_financieros_query_app($fecha, '1', '999')+
	indices_financieros_query_app($fecha, '2', '999')+indices_financieros_query($fecha, '3', '999')+
	indices_financieros_query_app_array('4', array('999', '091', '092', '093'), $fecha))/
	(indices_financieros_query_app($fecha, '5', '999')+indices_financieros_query_app($fecha, '6', '999')+
	indices_financieros_query_app($fecha, '7', '999')+indices_financieros_query_app($fecha, '8', '999')+
	indices_financieros_query_app($fecha, '9', '999')+indices_financieros_query_app($fecha, '10', '999')+
	indices_financieros_query_app($fecha, '11', '999')+indices_financieros_query_app($fecha, '12', '999')+
	indices_financieros_query_app($fecha, '13', '999'));
	return $anexo;
}

//apital de trabajo
//(Cuenta 110000  + anexo 142 Unid de Capt 01 reglon 999+unid de capt 02 reglon 999 +
//unidad de capt 03 reglon 999+ Und capt 04 reglones 999+091+092+093)-(anexo 142 unid de cap 05 reglon 999 + 
//unid  de cap 06 reglon 999+ unid de cap 07 reglon 999+ unidad de Cap 08 reglon 999+unidad de cap 09 reglon 999+ 
//unidad de capt 10 reglon 999+unid de capt  11 reglon 999+ unid de capt 12 reglon 999 + unid  de cap 013 reglon 999)
function indices_financieros_capital_trabajo($name, $id_actual, $id_anterior) {
	$res = '';
	$res .= '
				<div class = "codigo nivel_3">
				<div class = "column_1 ">' . $name . '</div>
				<div class = "column_2 ">'.formato_millones(indices_financieros_capital_trabajo_operacion($id_actual)).'</div>
				<div class = "column_3 ">'.formato_millones(indices_financieros_capital_trabajo_operacion($id_anterior)).'</div>
				</div>';
		return $res;
}

function indices_financieros_capital_trabajo_operacion($fecha) {
	$anexo = (indices_financieros_query($fecha, '11')+indices_financieros_query_app($fecha, '1', '999')+
	indices_financieros_query_app($fecha, '2', '999')+indices_financieros_query($fecha, '3', '999')+
	indices_financieros_query_app_array('4', array('999', '091', '092', '093'), $fecha))-
	(indices_financieros_query_app($fecha, '5', '999')+indices_financieros_query_app($fecha, '6', '999')+
	indices_financieros_query_app($fecha, '7', '999')+indices_financieros_query_app($fecha, '8', '999')+
	indices_financieros_query_app($fecha, '9', '999')+indices_financieros_query_app($fecha, '10', '999')+
	indices_financieros_query_app($fecha, '11', '999')+indices_financieros_query_app($fecha, '12', '999')+
	indices_financieros_query_app($fecha, '13', '999'));
	return $anexo;
}

//Concentracion endeudamiento a corto plazo 
//(cuenta 200000/(anexo 142 unid de cap 05 reglon 999 + unid  de cap 06 reglon 999+ 
//unid de cap 07 reglon 999+ unidad de Cap 08 reglon 999+unidad de cap 09 reglon 999+ 
//unidad de capt 10 reglon 999+unid de capt  11 reglon 999+ unid de capt 12 reglon 999 + unid  de cap 013 reglon 999)*100"
function indices_financieros_endeudamiento($name, $id_actual, $id_anterior) {
	$res = '';
	$res .= '
				<div class = "codigo nivel_3">
				<div class = "column_1 ">' . $name . '</div>
				<div class = "column_2 ">'.formato_porcentage(indices_financieros_endeudamiento_operacion($id_actual)).'</div>
				<div class = "column_3 ">'.formato_porcentage(indices_financieros_endeudamiento_operacion($id_anterior)).'</div>
				</div>';
		return $res;
}

function indices_financieros_endeudamiento_operacion($fecha) {
	$anexo = (indices_financieros_query($fecha, '2'))/
	(indices_financieros_query_app($fecha, '5', '999')+indices_financieros_query_app($fecha, '6', '999')+
	indices_financieros_query_app($fecha, '7', '999')+indices_financieros_query_app($fecha, '8', '999')+
	indices_financieros_query_app($fecha, '9', '999')+indices_financieros_query_app($fecha, '10', '999')+
	indices_financieros_query_app($fecha, '11', '999')+indices_financieros_query_app($fecha, '12', '999')+
	indices_financieros_query_app($fecha, '13', '999'))*100;
	return $anexo;
}

//endeudamiento total
//cuenta 200000/cuenta 100000)*100
function indices_financieros_endeudamiento_total($name, $id_actual, $id_anterior) {
	return '
				<div class = "codigo nivel_3">
				<div class = "column_1 ">' . $name . '</div>
				<div class = "column_2 ">'.formato_porcentage(((indices_financieros_query($id_actual, '2')/indices_financieros_query($id_actual, '1'))*100)).'</div>
				<div class = "column_3 ">'.formato_porcentage(((indices_financieros_query($id_anterior, '2')/indices_financieros_query($id_anterior, '1'))*100)).'</div>
				</div>';
}

//Laverage total 
//cuenta 200000/cuenta 300000)*100
function indices_financieros_laverage_total($name, $id_actual, $id_anterior) {
	return '
				<div class = "codigo nivel_3">
				<div class = "column_1 ">' . $name . '</div>
				<div class = "column_2 ">'.formato_porcentage(((indices_financieros_query($id_actual, '2')/indices_financieros_query($id_actual, '3'))*100)).'</div>
				<div class = "column_3 ">'.formato_porcentage(((indices_financieros_query($id_anterior, '2')/indices_financieros_query($id_anterior, '3'))*100)).'</div>
				</div>';
}

//Rotacion de activos totales 
//cuenta 410000/cuenta 100000)*100
function indices_financieros_rotacion($name, $id_actual, $id_anterior) {
	return '
				<div class = "codigo nivel_3">
				<div class = "column_1 ">' . $name . '</div>
				<div class = "column_2 ">'.formato_porcentage(((indices_financieros_query($id_actual, '41')/indices_financieros_query($id_actual, '1'))*100)).'</div>
				<div class = "column_3 ">'.formato_porcentage(((indices_financieros_query($id_anterior, '41')/indices_financieros_query($id_anterior, '1'))*100)).'</div>
				</div>';
}


// return valor puc
function indices_financieros_query($fecha, $cod) {
	$query = db_query('
		SELECT est_valor_reportado, field_codigo_puc_value 
		FROM estados_financieros, field_data_field_codigo_puc 
		WHERE est_entity_id = entity_id AND est_id_fecha = ' . $fecha . ' AND field_codigo_puc_value = '.$cod);
	if ($query != NULL) {
		$query = $query->fetchAssoc();
		return $query['est_valor_reportado'];
	} else {
		return .00;
	}
}

function indices_financieros_query_app($fecha, $cod, $cod_renglon) {
	$query = db_query('
		SELECT app_01 
		FROM activos_pasivos_patrimonio 
		WHERE app_fecha = '.$fecha.' AND app_renglon = '. $cod_renglon .' AND app_orden = '. $cod);
	
	if ($query != NULL) {
		$query = $query->fetchAssoc();
		return $query['app_01'];
	} else {
		return .00;
	} 
}

function indices_financieros_query_app_array($unidad ,$cod, $fecha) {
	$sum = 0; 
	foreach ($cod as $key => $value) {
		$sum = $sum + round(balance_general_query_app($fecha, $unidad, $value));
	}
	return $sum;
}