<?php
/**
 * Implements hook_block_info
 */
function valorem_informacion_economica_general_block_info() {
  $blocks = array();
  $blocks['info'] = array(
    'info' => t('Informacion Economica General')
  );
  $blocks['info2'] = array(
    'info' => t('Informacion Acciones y Accionistas')
  );
  return $blocks;
}

/**
 * Implements hook_block_view
 */
function valorem_informacion_economica_general_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'info':
      $block['subject'] = '<p class = "title">' . t('INFORMACION ECONOMICA GENERAL') . '</p>' . drupal_render(drupal_get_form('valorem_informacion_general_form'));
      $block['content'] =  '<div class = "nota-junta-up">' . l('super', 'http://superfinanciera.gov.co/web_valores/?MIval=Fechas_inf_fin&Tipo=066&Codigo=017&dibujo=simevcab.gif&titulo=Entidades%20Encontradas', array(
      	'attributes' => array(
      		'class' => 'super', 
      		'target'=>'_blank'
      	))) . '  <div class = "millones" style="display:none;">(' . t('Millones de pesos') . ') </div></div>' . 
      	valorem_informacion_general_page();
      break;
    case 'info2':
      $block['subject'] = '<p class = "title">' . t('INFORMACION GENERAL SOBRE ACCIONES Y ACCIONISTAS') . '</p>' . drupal_render(drupal_get_form('valorem_acciones_accionistas_form'));
      $block['content'] = '<div class = "nota-junta-up">' . l('super', 'http://superfinanciera.gov.co/web_valores/?MIval=Fechas_inf_fin&Tipo=066&Codigo=017&dibujo=simevcab.gif&titulo=Entidades%20Encontradas', array(
      	'attributes' => array(
      		'class' => 'super', 
      		'target'=>'_blank'
      	))) . '  <div class = "millones" style="display:none;">(' . t('Millones de pesos') . ') </div></div>' . 
      	valorem_acciones_accionistas_page();
      break;
    default:
      # code...
      break;
  }
  return $block;
}

/**
 *  function  balance_general_page autocomplete
 */
function valorem_informacion_general_page() {
  $id_anterior = 0;
  $id_actual = 0;
  if (isset ($_GET['id_periodo1']) && isset ($_GET['id_periodo2'])) {
    return valorem_informacion_general_consulta($_GET['id_periodo1'], $_GET['id_periodo2']);
  } else {
    $trimestre_actual = trimestre_actual();
    $ids = explode(',', $trimestre_actual);
    $id_anterior = $ids[0];
    $id_actual = isset($ids[1]) ? $ids[1] : 0;
    return valorem_informacion_general_consulta($id_actual, $id_anterior);
  }
}

function valorem_informacion_general_consulta($id_actual, $id_anterior) {
  if ($id_actual == 0) {
    $id_actual = $id_anterior;
    $id_anterior = 0;
  }
  $i = 0;
  $total = array();
  $valor_ant = 0;
  $valor_act = 0;
  $res_id_anterior = valorem_informacion_general_query($id_anterior);
  if ($res_id_anterior != NULL) {
    foreach ($res_id_anterior as $key => $value) {
      $total[$id_anterior][$value->info_descripcion] = array(
        'descripcion' => $value->info_descripcion,
        'valor' => $value->info_valor,
      );
    }
  }
  $res_id_actual = valorem_informacion_general_query($id_actual);
  if ($res_id_actual != NULL) {
    foreach ($res_id_actual as $key => $value) {
      $total[$id_actual][$value->info_descripcion] = array(
        'descripcion' => $value->info_descripcion,
        'valor' => $value->info_valor,
      );
    }
  }
  return valorem_informacion_general_construir_presentacion($total, $id_actual, $id_anterior);
}

function valorem_informacion_general_construir_presentacion($total, $id_actual, $id_anterior) {
  $res = '<div class = "informacion_general table-type-A column_count_3 notitle">';
  $res .= '<div class = "title">
    <div class = "column_1">' . t('Nombre') . '</div>
    <div class = "column_2">'.formato_fecha($id_actual).'</div>
    <div class = "column_3">'.formato_fecha($id_anterior).'</div>
    </div>'; 
  $total_anterior = isset($total[$id_anterior]) ? $total[$id_anterior] : array();
  $total_actual = isset($total[$id_actual]) ? $total[$id_actual] : array();
  $tabla = array();
  foreach ($total as $key => $value) {
    foreach ($value as $key2 => $value2) {
    	$tabla[$key][$value2['descripcion']] = $value2['valor']; 
		}
  }
	foreach ($tabla[$id_actual] as $key => $value) {
		$valor = isset($tabla[$id_anterior][$key]) ? $tabla[$id_anterior][$key] : '0.00';
		if (substr($key, 0, 11) == '% EMPLEADOS') {
			$res .= '
      <div class = "nivel_2">
      <div class = "column_1">' . $key . '</div>
      <div class = "column_2">% ' . $value . '</div>
      <div class = "column_3">% ' . $valor . '</div>
      </div>';
		} else {
			$res .= '
      <div class = "nivel_2">
      <div class = "column_1">' . $key . '</div>
      <div class = "column_2">' . $value . '</div>
      <div class = "column_3">' . $valor . '</div>
      </div>';	
		}
	}
  $res .= '</div>';
  return $res;
}

//consulta informacion balance general segun la fecha
function valorem_informacion_general_query($id_fecha) {
  $result = db_select('info_economica_general', 'n')
    ->fields('n')
    ->condition('info_fecha', $id_fecha,'=')
    ->execute();

  return $result;
}

/*
*  function form
*/
function valorem_informacion_general_form($form, &$form_state) {
  $trimestre_actual = trimestre_actual_indices_financieros();
  $ids = explode(',', $trimestre_actual);
  $id_anterior = $ids[0];
  $id_actual = isset($ids[1]) ? $ids[1] : 0;
  $form['periodo1'] = array(
    //'#title' => t('Periodo'),
    '#type' => 'select',
    '#options' => periodos_indices_financieros(),
    '#default_value' => isset ($_GET['id_periodo1']) ? $_GET['id_periodo1'] : $id_actual,
    '#weight' => -4,
  );
  $form['periodo2'] = array(
    //'#title' => t('Periodo'),
    '#type' => 'select',
    '#options' => periodos_indices_financieros(),
    '#default_value' => isset ($_GET['id_periodo2']) ? $_GET['id_periodo2'] : $id_anterior,
    '#weight' => -3,
  );
  $form['submit'] = array(
      '#type' => 'submit', 
      '#value' => t('Consultar')
  );
  return $form;
}

function valorem_informacion_general_form_validate($form, &$form_state) {
  $actual = $form_state['values']['periodo1'];
  $anterior = $form_state['values']['periodo2'];
  if (($actual == 'Periodo') && ($anterior == 'Periodo')) {
    form_set_error('periodo1', 'Seleccione Periodo');
    form_set_error('periodo2', 'Seleccione Periodo');
  } else {
    if (($actual == 'Periodo') || ($anterior == 'Periodo')) { 
    } else {
      $str_fecha = consultar_id_fecha_3($actual);
      $fecha_act = formatear_fecha_3($str_fecha);
      $str_fecha = consultar_id_fecha_3($anterior);
      $fecha_ant = formatear_fecha_3($str_fecha);
      if ($fecha_act == $fecha_ant) {
        form_set_error('periodo1', 'Periodos iguales');
        form_set_error('periodo2', 'Seleccione dos Periodos diferetes');
      }
    }
  }
}

function valorem_informacion_general_form_submit($form, &$form_state) {
  $actual = $form_state['values']['periodo1'];
  $anterior = $form_state['values']['periodo2'];
  //if (isset ($_GET['id_periodo1']) && isset ($_GET['id_periodo2'])) {
  $form_state['redirect'] = array('node/29', array(
    'query' => array('id_periodo1'=>$actual, 
      'id_periodo2'=>$anterior,
      'id'=>isset ($_GET['id']) ? $_GET['id'] : trimestre_actual_indices_financieros())));
}

/*Informacion Financiera acciones y accionistas*/
function valorem_acciones_accionistas_page() {
  $res = '';
  $id = 0;
  if (isset ($_GET['id'])) {
    $id = $_GET['id'];
  } 
  else { 
    $id = trimestre_actual_indices_financieros(); 
    $id = $id['id'];
  }
  
  //Arreglar la condicion para el ultimo reporte
  
  if ($id != 0) {
    return valorem_acciones_accionistas_construccion($id);
  }
  return t('No existen reportes') . ' <br> ' . t('para cargar informe trimestral, presione') . ' <a href= "#admin/config/user-interface/file_upload">' . t('aquí') . '</a>';
}

function valorem_acciones_accionistas_construccion($id) {
  $result = db_select('info_acciones_accionistas', 'n')
    ->fields('n')
    ->condition('inf_fecha', $id,'=')
    ->execute();
  $res = '<div class = "acciones_accionistas table-type-A column_count_3 notitle">
  		<div class = "title">
  			<div class = column_1>' . t('Descripción') . '</div>
     		<div class = column_2>' . t('No. DE ACCIONISTAS') . '</div>
      	<div class = column_3>' . t('No. DE ACCIONES') . '</div>
      </div>';
		$num_totales = 0;
	  foreach ($result as $key => $value) {
	  if ($value->inf_descripcion == 'TOTAL') {
	  	$num_totales++;
	  }	
		if (substr($value->inf_descripcion, 0, 18) == 'NUMERO DE ACCIONES' || $value->inf_descripcion == 'ACCIONES ORDINARIAS' || 
			$num_totales == 1 || $num_totales == 5 || $num_totales == 6 || $value->inf_descripcion == 'HASTA - 3.00%') {
			
					//Si es numero de acciones... este valor debe ser un número entero, así que quitamos decimales
					if (substr($value->inf_descripcion, 0, 18) == 'NUMERO DE ACCIONES') {
						$value->inf_acciones = str_replace('.00','',$value->inf_acciones);
					}
			
			
						$res .= '
					<div class = "nivel_2">
					<div class = column_1>'.$value->inf_descripcion.'</div>
					<div class = column_2>'.substr($value->inf_accionistas, 0, -3) .'</div>
					<div class = column_3>'.$value->inf_acciones.'</div>
				  </div>';
		} else {
						$res .= '
					<div class = "nivel_2">
					<div class = column_1>'.$value->inf_descripcion.'</div>
					<div class = column_2>% '.$value->inf_accionistas.'</div>
					<div class = column_3>'.$value->inf_acciones.'</div>
				  </div>';	
		}
    //<div class = column_2>% '.number_format($value->inf_accionistas).'</div>
  }
  $res .= '</div>';
  return $res;
}

function valorem_acciones_accionistas_form($form, &$form_state) {
  $ids = explode(',', trimestre_actual_indices_financieros());
	$id_anterior = $ids[0];
  $id_actual = isset($ids[1]) ? $ids[1] : 0;
  $form['periodo'] = array(
    '#type' => 'select',
    '#options' => periodos_indices_financieros(),
    '#default_value' => isset ($_GET['id']) ? $_GET['id'] : $id_actual,
  );
  $form['submit'] = array(
    '#type' => 'submit', 
    '#value' => t('Consultar')
  );
   return $form;
}

function valorem_acciones_accionistas_form_submit($form, &$form_state) {
  $id_fecha = $form_state['values']['periodo'];
	$ids = explode(',', trimestre_actual_indices_financieros());
	$id_anterior = $ids[0];
  $id_actual = isset($ids[1]) ? $ids[1] : 0;
  $form_state['redirect'] = array('node/29', array('query' => array(
    'id_periodo1'=> isset ($_GET['id_periodo1']) ? $_GET['id_periodo1'] : $id_fecha, 
    'id_periodo2'=> isset ($_GET['id_periodo2']) ? $_GET['id_periodo2'] : $id_anterior,
    'id'=>$id_fecha)));
}